function have_binary(){return have_nplastpass()||have_native_messaging()||have_ws()}function have_binary_function(a){return have_nplastpass()&&"function"==typeof g_nplastpass[a]?!0:have_native_messaging()&&lp_in_array(a,g_native_messaging_functions)?!0:have_ws()&&lp_in_array(a,g_ws_functions)?!0:!1}
function call_binary_function(){if(0<arguments.length){for(var a=arguments[0],b=[],d=null,c=1;c<arguments.length;c++)c==arguments.length-1&&"function"==typeof arguments[c]?d=arguments[c]:b[b.length]=arguments[c];if(have_nplastpass()&&"function"==typeof g_nplastpass[a]){var e;0==b.length?e=g_nplastpass[a]():1==b.length?e=g_nplastpass[a](b[0]):2==b.length?e=g_nplastpass[a](b[0],b[1]):3==b.length?e=g_nplastpass[a](b[0],b[1],b[2]):4==b.length?e=g_nplastpass[a](b[0],b[1],b[2],b[3]):5==b.length?e=g_nplastpass[a](b[0],
b[1],b[2],b[3],b[4]):6==b.length?e=g_nplastpass[a](b[0],b[1],b[2],b[3],b[4],b[5]):lplog("too many arguments passed to call_binary_function, funcname="+a+", argslen="+b.length);d&&d(e)}else if(have_native_messaging()&&lp_in_array(a,g_native_messaging_functions)){e={cmd:a,argcount:b.length};for(c=0;c<b.length;c++)e["arg"+c]=b[c];var f;"get_chrome_passwords"==a&&(f=d,d=function(a){f(JSON.parse(a))});native_messaging_send_message(e,d)}else if(lp_ws&&lp_ws.isconnected()&&lp_in_array(a,g_ws_functions)){e=
{cmd:a,argcount:b.length};for(c=0;c<b.length;c++)e["arg"+c]=b[c];ws_send_message(e,d)}}}function call_binary_function_if(){if(0<arguments.length)if(have_binary_function(arguments[0]))call_binary_function.apply(this,arguments);else if(1<arguments.length&&"function"==typeof arguments[arguments.length-1])arguments[arguments.length-1](!1)}
function resolveToFile(a){switch(a.scheme){case "chrome":return resolveToFile(g_chrome.Cc["@mozilla.org/chrome/chrome-registry;1"].getService(g_chrome.Ci.nsIChromeRegistry).convertChromeURL(a));case "resource":return resolveToFile(g_chrome.Cu.import("resource://gre/modules/Services.jsm").Services.io.newURI(g_chrome.Cu.import("resource://gre/modules/Services.jsm").Services.io.getProtocolHandler("resource").QueryInterface(g_chrome.Ci.nsIResProtocolHandler).resolveURI(a),null,null));case "file":return a.QueryInterface(g_chrome.Ci.nsIFileURL).file;
default:throw Error("Cannot resolve");}}var lpctypes=null,lpctypeslib=null,lpctypesabi=null,lpctypesfree=null,lpctypes_call_binary_function=null,g_native_messaging=null,g_native_messaging_loaded=!1,g_native_messaging_functions=[],g_native_messaging_version=gs("Unknown"),g_native_messaging_build_date=gs("Unknown"),g_native_messaging_build_time=gs("Unknown");
function connect_native_messaging(){try{if(g_isfirefoxsdk){if(!g_is_win&&!g_is_mac&&!g_is_linux)return;var a;g_is_win?a=-1!=g_system.architecture.indexOf("64")?"nplastpass64.dll":"nplastpass.dll":g_is_mac?a="nplastpass.bundle/Contents/MacOS/nplastpass":g_is_linux&&(a=-1!=g_system.architecture.indexOf("64")?"libnplastpass64.so":"libnplastpass.so");a=resolveToFile(g_chrome.Cu.import("resource://gre/modules/Services.jsm").Services.io.newURI(self.data.url(a),null,null));if(!a.exists())return;lpctypes=
g_chrome.Cu["import"]("resource://gre/modules/ctypes.jsm").ctypes;lpctypeslib=lpctypes.open(a.path);lpctypesabi=g_is_win&&-1==g_system.architecture.indexOf("64")?lpctypes.winapi_abi:lpctypes.default_abi;lpctypesfree=lpctypeslib.declare("lp_free",lpctypesabi,lpctypes.void_t,lpctypes.void_t.ptr);lpctypes_call_binary_function=function(a){try{var b=lpctypeslib.declare("call_binary_function",lpctypesabi,lpctypes["char"].ptr,lpctypes["char"].ptr)(a),e;b.isNull()?e="":(e=b.readString(),lpctypesfree(b));
return e}catch(f){return""}}}else{if("undefined"==typeof chrome||"undefined"==typeof chrome.extension||"undefined"==typeof chrome.extension.connectNative)return;g_native_messaging=chrome.extension.connectNative("com.lastpass.nplastpass");g_native_messaging.onMessage.addListener(native_messaging_message);g_native_messaging.onDisconnect.addListener(function(){g_native_messaging_loaded=!1;lplog("native messaging host disconnected");"undefined"!=typeof chrome.extension.lastError&&"undefined"!=typeof chrome.extension.lastError.message&&
lplog("last error: "+chrome.extension.lastError.message)})}native_messaging_send_message({cmd:"get_function_names",argcount:0},function(a){a&&(g_native_messaging_functions=a.split(","),g_native_messaging_loaded=!0,localStorage_setItem("hadNativeMessaging","1"),setup_wlan_variables(),setup_is_chrome_portable(),!have_nplastpass()&&g_onload_started&&onLoad(!0))});native_messaging_send_message({cmd:"get_version",argcount:0},function(a){0>=CompareLastPassVersions(a,"3.0.15")?(g_native_messaging_loaded=
!1,g_native_messaging.disconnect(),lplog("blocked old native messaging host version "+a)):g_native_messaging_version=a});native_messaging_send_message({cmd:"get_build_date",argcount:0},function(a){g_native_messaging_build_date=a});native_messaging_send_message({cmd:"get_build_time",argcount:0},function(a){g_native_messaging_build_time=a})}catch(b){}}var g_native_messaging_parts=[];
function native_messaging_message(a,b,d){if("undefined"!=typeof a.id){b=d?g_ws_callbacks:g_native_messaging_callbacks;lpdbg("nativemessaging","got message, id="+a.id);d=!1;if("undefined"!=typeof a.retval)d=!0;else if("undefined"!=typeof a.parts&&"undefined"!=typeof a.part&&"undefined"!=typeof a.retvalpart){if("undefined"==typeof g_native_messaging_parts[a.id]){g_native_messaging_parts[a.id]=[];for(var c=0;c<a.parts;c++)g_native_messaging_parts[a.id][c]=null}g_native_messaging_parts[a.id][a.part]=
a.retvalpart;d=!0;for(c=0;c<a.parts;c++)if(null==g_native_messaging_parts[a.id][c]){d=!1;break}if(d){a.retval="";for(c=0;c<a.parts;c++)a.retval+=g_native_messaging_parts[a.id][c];g_native_messaging_parts[a.id]=null}}d&&"function"==typeof b[a.id]&&(d=b[a.id],b[a.id]=null,d(a.retval))}else if("undefined"!=typeof a.cmd)switch(lpdbg("nativemessaging","got message, cmd="+a.cmd),a.cmd){case "namedpipeobserverfunction":namedpipeobserverfunction(a.arg0,a.arg1,a.arg2);break;case "basicauth_save":basicauth_save(a.arg0,
a.arg1,a.arg2,a.arg3);break;case "basicauth_found":basicauth_found(a.arg0,a.arg1,a.arg2)}}function have_native_messaging(){return g_native_messaging_loaded}function have_ws(){return lp_ws&&lp_ws.isconnected()}var g_native_messaging_callbacks={};
function native_messaging_send_message(a,b){try{var d=(new Date).getTime()+"_"+Math.floor(100*Math.random());lpdbg("nativemessaging","sending message, cmd="+("undefined"!=typeof a.cmd?a.cmd:"undefined")+", id="+d);a.id=d;if(g_isfirefoxsdk){a.extension_url=window.location.href;var c=lpctypes_call_binary_function(JSON.stringify(a));"function"==typeof b&&b(JSON.parse(c).retval)}else g_native_messaging_callbacks[d]=b,g_native_messaging.postMessage(a)}catch(e){}}var g_ws_parts={},chunk_size=5E4;
function ws_send_part(a,b){var d=g_ws_parts[a].message,c=g_ws_parts[a].arg;d.part=b;d["arg"+d.argpart]=c.substring(b*chunk_size,(b+1)*chunk_size);g_ws_callbacks[a]=b>=d.parts-1?function(b){g_ws_parts[a].callback(b);g_ws_parts[a]=null}:function(b){ws_send_part(a,b+1)};lp_ws.send(LPJSON.stringify(d))}var g_ws_callbacks={};
function ws_send_message(a,b){try{var d=(new Date).getTime()+"_"+Math.floor(100*Math.random());a.id=d;var c=-1;if(g_ischrome)for(var e=0;e<a.argcount;e++)if("string"==typeof a["arg"+e]&&a["arg"+e].length>chunk_size){c=e;break}if(-1!=c){var f=a["arg"+c];a.cmdparts=a.cmd;delete a.cmd;a.argpart=c;a.parts=Math.ceil(f.length/chunk_size);g_ws_parts[d]={message:a,arg:f,callback:b};ws_send_part(d,0)}else g_ws_callbacks[d]=b,lp_ws.send(LPJSON.stringify(a))}catch(g){}}
function test_native_messaging(a){try{if(g_isfirefoxsdk)a(!0);else if(!g_ischrome||"undefined"==typeof chrome||"undefined"==typeof chrome.permissions||"undefined"==typeof chrome.permissions.contains)g_do_native_messaging=!1;else{var b=navigator.userAgent.match(/Chrome\/(\d+)/);b&&29>parseInt(b[1])?g_do_native_messaging=!1:!g_is_win&&!g_is_mac&&!g_is_linux?g_do_native_messaging=!1:chrome.permissions.contains({permissions:["nativeMessaging"]},a)}}catch(d){g_do_native_messaging=!1}}
function request_native_messaging(a){getBG().lpPutGblPref("native_messaging_asked","1");a?openURL(getchromeurl("native_messaging.html?hidenever=1")):chrome.permissions.request({permissions:["nativeMessaging"]},function(a){a&&alert(gs("Please restart your browser to finish enabling native messaging."))})}function native_messaging_never_ask_again(){var a=getBG();a.lpPutGblPref("native_messaging_never_ask_again","1");a.lpWriteAllPrefs();a.closecurrenttab("native_messaging.html")}
var g_ask_native_messaging_from_button=!1;function open_native_messaging_html_if(){g_open_native_messaging_html&&!have_nplastpass()&&"1"!=lpGetPref("native_messaging_never_ask_again","0")&&lpGetPref("native_messaging_asked","0")}function install_binary(a,b){g_do_native_messaging&&!a&&!g_have_native_messaging_permission&&supports_native_messaging()?request_native_messaging(b):openURL(base_url+"installer/")}var g_debug_nplastpass=!0;
function debug_nplastpass(a){g_debug_nplastpass&&lpdbg("nplastpass",a)}var g_nplastpass_loaded=!1;
function have_nplastpass(a){debug_nplastpass("checking for binary component");try{g_nplastpass&&(g_nplastpass_loaded&&"undefined"==typeof g_nplastpass.alert)&&(debug_nplastpass("binary component loaded but alert function not found, resetting"),g_nplastpass=null)}catch(b){debug_nplastpass("caught exception while resetting binary component: "+b.message)}if(!g_nplastpass){debug_nplastpass("attempting to setup binary component");for(var d=0;d<(g_issafari?2:1);d++)try{if(0==d){if(debug_nplastpass("setting binary component global"),
g_nplastpass=document.getElementById("nplastpass"),!g_nplastpass&&g_isopera&&allow_nplastpass()){var c=document.createElement("embed");c.setAttribute("id","nplastpass");c.setAttribute("type","application/x-vnd-lastpass");document.body.appendChild(c);g_nplastpass=c}}else if(g_issafari)for(var e=0;e<safari.extension.bars.length;e++)if("LPMenu"==safari.extension.bars[e].identifier){var f=safari.extension.bars[e].contentWindow.document;f.getElementById("nplastpass")&&f.body.removeChild(f.getElementById("nplastpass"));
c=f.createElement("embed");c.setAttribute("id","nplastpass");c.setAttribute("type","application/x-vnd-lastpass");c.style.visibility="hidden";f.body.appendChild(c);g_nplastpass=c;break}debug_nplastpass("type of alert is "+typeof g_nplastpass.alert);debug_nplastpass("checking for chrome portable");g_nplastpass.is_chrome_portable();debug_nplastpass("checking for wlan stuff");setup_wlan_variables();setup_is_chrome_portable();debug_nplastpass("checking for alert function");(g_nplastpass_loaded="undefined"!=
typeof g_nplastpass.alert)?debug_nplastpass("binary component is loaded"):debug_nplastpass("binary component failed to load");break}catch(g){debug_nplastpass("caught exception while setting up binary component: "+g.message),g_nplastpass=null}}g_debug_nplastpass=!1;try{return"undefined"!=typeof g_nplastpass.alert&&(a||-1==navigator.userAgent.indexOf("Chrome/4.1.249.1042"))}catch(h){return!1}}
function get_nplastpass_version(){return have_nplastpass()&&"function"==typeof g_nplastpass.get_version?g_nplastpass.get_version():gs("Unknown")}function get_nplastpass_build_date_time(){return have_nplastpass()&&"function"==typeof g_nplastpass.get_build_date&&"function"==typeof g_nplastpass.get_build_time?g_nplastpass.get_build_date()+" "+g_nplastpass.get_build_time():gs("Unknown")}
function close_lpctypeslib(){g_isfirefoxsdk&&lpctypeslib&&(ctypeslib=lpctypeslib,g_native_messaging_loaded=!1,lpctypeslib=lpctypesfree=null,g_is_mac||ctypeslib.close())};
