function redraw_menu(){var f=getBG().lploggedin,c=!1,e;for(e in getBG().g_sites)if("1"==getBG().g_sites[e].fav&&getBG().check_ident_aid(e)){c=!0;break}c=[{hidden:f,cmd:"getBG().lplogin()",icon:"images/power_off.png",title:getBG().gs("Login")},{hidden:f,title:'<select style="visibility: hidden;"></select>'},{hidden:!f,cmd:"getBG().lplogoff(false,'menu1')",icon:"images/power_off.png",title:getBG().gs("Log out")},{hidden:!f||getBG().g_hidevault,cmd:"getBG().openvault()",icon:"images/icon_vault.png",
title:getBG().gs("My LastPass Vault")},{hidden:!f,menu:"sites",icon:"images/icon_sites.png",title:getBG().gs("Sites")},{hidden:!f||getBG().g_hideopenfavs||!c,cmd:"getBG().openfavorites()",icon:"images/icon_favorites.png",title:getBG().gs("Open Favorites")},{hidden:!f,menu:"fillforms",icon:"images/icon_formfill.png",title:getBG().gs("Fill Forms")},{hidden:!f,menu:"tools",icon:"images/icon_tools.png",title:getBG().gs("Tools")}];getBG().LPISLOC?c.push({hidden:!f,cmd:"getBG().upgradetoserver()",icon:"images/icon_premium.png",
title:getBG().gs("Upgrade to LastPass Online!")}):c.push({hidden:!f||getBG().g_hidegopremium||getBG().g_premium_exp>lp_get_local_timestamp()||getBG().g_enterpriseuser,cmd:"getBG().openpremium()",icon:"images/icon_premium.png",title:getBG().gs("Go Premium!")});c.push({hidden:!f,cmd:"getBG().saveall()",icon:"images/icon_saveall.png",title:getBG().gs("Save All Entered Data")});var g;g='<table cellspacing="0" cellpadding="0"><tr>';var l=!0;for(e=0;e<c.length;e++)if(!c[e].hidden){!l&&f&&(g+='<td style="font-size: 16px;">&nbsp;&nbsp;|&nbsp;&nbsp;</td>');
var l=!1,j="",k="";"undefined"!=typeof c[e].cmd&&(j='<a href="javascript:'+c[e].cmd+';getBG().close_menu();">',k="</a>");var d="";if("undefined"!=typeof c[e].menu){var a;switch(c[e].menu){case "sites":a=[];for(var d=getBG().getmatchingsites(),b=0;b<d.length;b++){var h=of(d[b].name);""!=d[b].username&&(h+=" ("+of(d[b].username)+")");a.push({cmd:"getBG().fillaid("+d[b].aid+")",title:h})}break;case "fillforms":a=[{cmd:"getBG().addprofile()",title:getBG().gs("Add Profile")},{cmd:"getBG().addcreditcard()",
title:getBG().gs("Add Credit Card")},{cmd:"getBG().clearforms()",title:getBG().gs("Clear Forms")},{cmd:"getBG().openchooseprofilecc()",title:getBG().gs("Choose Profile and Credit Card")}];d=!0;for(b=getBG().g_formfills.length-1;0<=b;b--)getBG().check_ident_ffid(getBG().g_formfills[b].ffid)&&(d&&(a.unshift({title:"----------"}),d=!1),a.unshift({cmd:"getBG().fillform("+getBG().g_formfills[b].ffid+")",title:of(getBG().g_formfills[b].decprofilename)}));break;case "tools":a=[{cmd:"getBG().opengenpw()",
title:getBG().gs("Generate Secure Password")},{cmd:"getBG().openprefs()",title:getBG().gs("Preferences")}],getBG().g_hidesearch||a.push({cmd:"getBG().opensearch()",title:getBG().gs("Site Search")}),getBG().g_hiderecheckpage||a.push({cmd:"getBG().recheckpage()",title:getBG().gs("Recheck Page")}),getBG().LPISLOC||(a.push({cmd:"getBG().refreshsites()",title:getBG().gs("Refresh Sites")}),getBG().g_hideimport||a.push({cmd:"getBG().openimport()",title:getBG().gs("Import")})),getBG().g_hideexport||a.push({cmd:"getBG().doexportchoose()",
title:getBG().gs("Export")}),!getBG().LPISLOC&&!getBG().g_hideprint&&(a.push({cmd:"getBG().openprint(false)",title:getBG().gs("Print Sites")}),getBG().g_hidenotes||a.push({cmd:"getBG().openprint(true)",title:getBG().gs("Print Secure Notes")})),getBG().g_hidecheckupdates||a.push({cmd:"getBG().checkforupdates()",title:getBG().gs("Check For Updates")}),getBG().LPISLOC||(a.push({cmd:"getBG().clearCache(false)",title:getBG().gs("Clear Local Cache")}),getBG().g_hideseccheck||a.push({cmd:"getBG().openseccheck()",
title:getBG().gs("Security Check")}),getBG().g_hidesessions||a.push({cmd:"getBG().opensessions()",title:getBG().gs("Other Sessions")})),a.push({cmd:"getBG().openhelp()",title:getBG().gs("Help...")}),getBG().g_hideabout||a.push({cmd:"getBG().openabout()",title:getBG().gs("About...")}),a.push({title:"----------"}),a.push({cmd:"getBG().openaddsite()",title:getBG().gs("Add Site")}),getBG().g_hidenotes||a.push({cmd:"getBG().openaddsecurenote()",title:getBG().gs("Add Secure Note")})}d=': <select style="width: 75px;" onchange="eval(this.options[this.selectedIndex].value);"><option>'+
getBG().gs("Select")+"</option>";for(b=0;b<a.length;b++)h="","undefined"!=typeof a[b].cmd&&(h+=a[b].cmd+"; getBG().close_menu();"),h+="this.selectedIndex = 0;",d+='<option value="'+h+'">'+a[b].title+"</option>";d+="</select>"}b="";"undefined"!=typeof c[e].icon&&(g+="<td>"+j+'<img border="0" src="'+getchromeurl(c[e].icon)+'">'+k+"</td>",b="&nbsp;");g+="<td>"+j+b+c[e].title+k+d+"</td>"}g+="</tr></table>";document.body.innerHTML=g}
"undefined"!=typeof safari&&("undefined"!=typeof safari.extension.globalPage&&safari.extension.globalPage)&&getBG().drawIconAtRotation(0);
