var gLastLoginState=0,gAccts_version=-1,gCurr_username="",gTimerId=null,gIconsLength=0,gLastSearch="",gIdentity="",gSearchWhileType=!0,gTreeHeightOffset=147,gPollInterval=500,gHidePreferences=!1,gLocalBaseUrl="",g_hideprofilecopy=1,g_hideidentcopy=1,g_localvault=1,g_showrows=1,g_autoselectcredmontab=0,g_partnername="",g_hideenterprisetab=!1,g_CNTsearch_it=0,g_CNTsearch_string_tokenize=0,g_CNTinit_vault=0,g_CNTpopulate=0,g_CNTsearch_tree=0,g_CNTclear_tree=0,event_handlers={},event_handlers_onmouseover=
{},event_handlers_onmouseout={},event_handlers_onclick={},styles={},VIEWS={TREE:0,GRID:1},g_view=VIEWS.TREE;function getpartnerurl(a){""!=g_partnername&&(a+=(0<=a.indexOf("?")?"&":"?")+"partnername="+encodeURIComponent(g_partnername));return a}function fix_group(a){a==g_xlat_none&&(a="");return a}
function onLoad(a,b){try{if("undefined"!=typeof g_is_safari&&"undefined"==typeof LPFromWebsite)50>a?(a++,setTimeout(function(){onLoad(a)},25)):document.location.href=document.location.href;else if("undefined"==typeof g_is_safari&&!b)get_data("vault",function(){onLoad(a,!0)});else if("function"!=typeof getBG||"undefined"==typeof getBG()||null==getBG())setTimeout(function(){onLoad()},50);else{var c=getBG();g_urlprefix=c.base_url;var f=document.createElement("base");f.href=g_urlprefix;document.head.appendChild(f);
0<document.location.href.lastIndexOf("/")&&(gLocalBaseUrl=document.location.href.substr(0,document.location.href.lastIndexOf("/")+1));c.LPISLOC&&(document.getElementById("accountsettingscontainer").style.display="none");c.g_hideidentities&&(document.getElementById("identitycontainer").style.display="none");c.g_hideseccheck&&(document.getElementById("seccheckcontainer").style.display="none");sr(document,"submit","value","Searchproper");document.getElementById("q").setAttribute("placeholder",gs("Search Vault"));
document.getElementById("lpusername").innerHTML="<b><a href='' id='lpusernamelink'>"+gs("Log in")+"</a></b>";onResize();inittabs();setusernametext(c.g_username);0<document.location.href.indexOf("grid=1")&&(g_view=VIEWS.GRID);gTimerId=setInterval(function(){checkLoggedInHome()},gPollInterval);var g=getcolvisibility("usernamecol"),h=getcolvisibility("ltnamecol");document.getElementById("usercol").className=g?"usercolvisible":"usercolhidden";document.getElementById("ltcol").className=h?"ltcolvisible":
"ltcolhidden";document.getElementById("ltcol").style.paddingRight=g?"calc(5% + 20px)":"5%";create_combo("grpsel",[]);document.getElementById("grpsel_combo").style.height="150px";document.getElementById("grpsel_combo").style.overflow="auto";document.getElementById("q").focus();c&&convert_object_to_array(c.g_identities).length?showhide_ident_actions(I_SHOW):showhide_ident_actions(I_HIDE);document.getElementById("shares").style.display=c.g_hidesharing?"none":"table-cell";document.getElementById("addsecurenote").style.display=
c.g_hidenotes?"none":"block";document.getElementById("lpimport").style.display=c.g_hideimport?"none":"block";document.getElementById("lpexport").style.display=c.g_hideexport?"none":"block";g_xlat_runame=gs("recently usedlower");g_xlat_pendingname=gs("(New Pending Share Offers)");g_xlat_favorites=gs("favorites");g_xlat_edit=gs("Edit");g_xlat_delete=gs("Delete");g_xlat_share=gs("Share");g_xlat_none=gs("(none)");g_xlat_chpw=gs("Change Password")}}catch(l){alert("homelocal2 onLoad:"+l)}}
function onUnLoad(){gTimerId&&(clearInterval(gTimerId),gTimerId=null);saveGroupState()}
function onResize(){for(var a=0;a<tabnames.length;a++)document.getElementById(tabnames[a])&&(document.getElementById(tabnames[a]).style.height=document.body.clientHeight-gTreeHeightOffset+20+"px");document.getElementById("thetree")&&(document.getElementById("thetree").style.height=document.body.clientHeight-gTreeHeightOffset-14+"px");document.getElementById("thegrid")&&(document.getElementById("thegrid").style.height=document.body.clientHeight-gTreeHeightOffset+20+"px")}
function checkLoggedInHome(a){try{var b=getBG(),c=b.lploggedin;if(("undefined"!=typeof g_issafari&&g_issafari||"undefined"!=typeof g_isopera&&g_isopera||"undefined"!=typeof g_ismaxthon&&g_ismaxthon||"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk)&&!a)b.update_state("vault");else{a="";c&&(a=b.g_username,refresh_ident_actions());if(c!=gLastLoginState||a!=gCurr_username)if(g_cachedOpenGroups=null,c)window_load_loggedin(a);else{try{var f={"static":"{}"};g_view==VIEWS.TREE?$(function(){$("#thetree").tree({data:{type:"json",
opts:f}})}):$("#thegrid").empty()}catch(g){}finish_vault_search();g_lastnodeid=g_rootnodeid=null;window_load_loggedoff();update_identity_popup()}gLastLoginState=c;g_username=lpusername=gCurr_username=a;if(gLastLoginState){var h=b.g_local_accts_version;if(h>gAccts_version||b.IsIconsUpdated(gIconsLength)||b.g_identity!=gIdentity)finish_vault_search(),gAccts_version=h,massoperation=!0,populateNewData(gLastSearch),massoperation=!1,saveGroupState(),populateff(gLastSearch),populateident(gLastSearch),update_identity_popup(),
setusernametext(a),showads()}}}catch(l){alert("checkLoggedInHome:"+l)}}
function setusernametext(a){var b=getBG(),c=document.getElementById("lplogoff");if(b.lploggedin){c.style.display="block";var c="",f;for(f in b.g_identities)if(b.g_identities.hasOwnProperty(f)&&b.g_identity==b.g_identities[f].iid){c=b.g_identities[f].deciname;break}""==c?set_innertext(document.getElementById("lpusername"),of(a)):set_innertext(document.getElementById("lpusername"),of(a+" ("+c+")"))}else document.getElementById("lpusername").innerHTML="<b><a href='' id='lpusernamelink'>"+gs("Login")+
"</a></b>",c&&(c.style.display="none")}
function window_load_loggedin(a){document.getElementById("identity").disabled=0;document.getElementById("enterpriseaction").style.display=!g_hideenterprisetab&&getBG().g_iscompanyadmin?"list-item":"none";document.getElementById("enterprise").style.display=g_hideenterprisetab||"1"==getBG().g_enterpriseuser?"none":"table-cell";"1"==getBG().g_enterpriseuser&&(document.getElementById("lpfriendemail").style.display=document.getElementById("lpgift").style.display="none");document.getElementById("addsharedfolder").style.display=
"list-item";document.getElementById("credmon").style.display="1"==getBG().g_showcredmon?"table-cell":"none";document.getElementById("linkpersonal").style.display="1"==getBG().g_enterpriseuser&&!g_hideenterprisetab&&""==get_personal_linked()?"list-item":"none";document.getElementById("removepersonal").style.display="1"==getBG().g_enterpriseuser&&!g_hideenterprisetab&&""!=get_personal_linked()?"list-item":"none";setusernametext(a);getBG().get_securityChallengeScore(function(a){var c=!1,f;for(f in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(f)){c=
!0;break}a&&c&&(document.getElementById("securitycheckscore").style.display="block",document.getElementById("securitycheckscore").style.color="#fff",document.getElementById("securitycheckscore").style.backgroundColor=getscorecolor(a),document.getElementById("securitycheckscore").innerHTML=parseInt(a)+"%",document.getElementById("securitycheckscore").style.display="inline")});g_local_key=getBG().g_local_key;g_key_iterations=getBG().get_key_iterations(a)}
function showads(){getBG().lploggedin&&getBG().g_premium_exp<lp_get_local_timestamp()&&"1"!=getBG().g_enterpriseuser&&-1==document.location.href.indexOf("cmd=video")?("none"==getComputedStyle(document.getElementById("adframe")).display&&(document.getElementById("adframe").style.display="block",document.getElementById("rightside").style.display="block",document.getElementById("adframe").setAttribute("src",getpartnerurl(g_urlprefix+"ads.php?nobr=1&noga=1&rand="+Math.floor(1E3*Math.random())))),document.getElementById("friend").style.display=
"block"):(document.getElementById("adframe").style.display="none",document.getElementById("rightside").style.display="none",document.getElementById("friend").style.display="none")}
function window_load_loggedoff(){gAccts_version=-1;gIconsLength=0;g_local_key=null;document.getElementById("lpusername").innerHTML="<b><a href='' id='lpusernamelink'>"+gs("Login")+"</a></b>";document.getElementById("q").value="";document.getElementById("credmon").style.display="none";document.getElementById("adframe").style.display="none";document.getElementById("rightside").style.display="none";document.getElementById("friend").style.display="none";document.getElementById("enterpriseaction").style.display=
"none";document.getElementById("enterprise").style.display=g_hideenterprisetab?"none":"table-cell";document.getElementById("addsharedfolder").style.display="none";document.getElementById("linkpersonal").style.display="none";document.getElementById("removepersonal").style.display="none";for(var a=0;a<tabnames.length;a++)"treepane"!=tabnames[a]&&cleartab(tabnames[a]);setusernametext(getBG().g_username);document.getElementById("securitycheckscore").style.display="none"}
function populateNewData(a){var b=!1,c;for(c in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(c)){b=!0;break}if(!b)for(c in getBG().g_securenotes)if(getBG().g_securenotes.hasOwnProperty(c)){b=!0;break}var f=!1;for(c in getBG().g_pendings)if(getBG().g_pendings.hasOwnProperty(c)){f=!0;break}!b&&!f?document.getElementById("sitesiframe")||(b=document.getElementById("treepane"),a=document.createElement("iframe"),a.id="sitesiframe",a.className="overviewiframe",a.src=getpartnerurl("sites_overview.php?version="+
encodeURIComponent(lpversion)),b.appendChild(a),document.getElementById("thetree").style.display="none",document.getElementById("thegrid").style.display="none"):(document.getElementById("sitesiframe")&&(b=document.getElementById("treepane"),b.removeChild(document.getElementById("sitesiframe")),g_view==VIEWS.TREE?document.getElementById("thetree").style.display="block":document.getElementById("thegrid").style.display="block"),g_view==VIEWS.TREE?($("#thetree").show(),$("#headerli").show(),$("#thegrid").hide()):
($("#thetree").hide(),$("#headerli").hide(),$("#thegrid").show()),populate(a,!0),SearchTree(0,!0,!0))}function isSafariNative(){return"undefined"!=typeof LPFromWebsite&&("undefined"==typeof g_issafari||!g_issafari)}
function update_identity_popup(){for(var a=getBG(),b=document.getElementById("identity");b.length;)b.remove(0);var c=document.createElement("option");c.text=gs("All");c.value="";""==a.g_identity&&(c.selected=1);b.appendChild(c);var f=0,g;for(g in a.g_identities)a.g_identities.hasOwnProperty(g)&&(c=document.createElement("option"),c.text=a.g_identities[g].deciname,c.value=a.g_identities[g].iid,a.g_identity==a.g_identities[g].iid&&(c.selected=1),b.appendChild(c),f++);0<f&&!getBG().g_hideidentities?
document.getElementById("identitycontainer").style.display="block":document.getElementById("identitycontainer").style.display="none"}
function search_matches(a,b){var c=getBG(),c=c.g_prompts.edit_sn_prompt?!1:c.get_searchNotesPref();g_CNTsearch_matches++;var f=getBG().g_sites[a];if("undefined"==typeof f&&(f=getBG().g_securenotes[a],"undefined"==typeof f&&(0==a.indexOf("app")&&(a=a.substring(3)),f=getBG().g_applications[a],"undefined"==typeof f&&(f=getBG().g_pendings[a],"undefined"==typeof f)))){var g=getgroupnamefromid(a);if(g)for(var h in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(h)&&"undefined"!=typeof getBG().g_sites[h]&&
"http://group"==getBG().g_sites[h].url&&getBG().g_sites[h].group==g){f=getBG().g_sites[h];break}if("undefined"==typeof f)return!1}return matches(f,b,c)}var g_all_li=[],g_search_array={};function init_vault_search(){g_all_li=$("#thetree").find("li");g_CNTinit_vault++;var a=getBG(),a=a.g_prompts.edit_sn_prompt?!1:a.get_searchNotesPref();g_search_array=sites_tokenize(g_all_li,a)}function finish_vault_search(){lastqstr=g_search_array=g_all_li=null}
function sites_tokenize(a,b){for(var c={},f=0;f<a.length;f++){var g=a[f].id,h="id"+g,l="",j=getBG().g_sites[g];if("undefined"==typeof j&&(j=getBG().g_securenotes[g],"undefined"==typeof j&&(0==g.indexOf("app")&&(g=g.substring(3)),j=getBG().g_applications[g],"undefined"==typeof j&&(j=getBG().g_pendings[g],"undefined"==typeof j))))if(g=getgroupnamefromid(g))l=g;else if("undefined"==typeof j)continue;if(l)j=l.toLowerCase(),c[h]=j;else if("undefined"!=typeof j){l=[];l.push(j.name);l.push(j.group);"http://group"!=
j.url&&"http://sn"!=j.url&&l.push(j.url);j.unencryptedUsername&&l.push(j.unencryptedUsername);is_application(j)&&(l.push(j.appname),l.push(getusernamefromacct(j)));if(b&&"undefined"!=typeof j.extra&&0<j.extra.length&&("undefined"==typeof j.url||"http://group"!=j.url)&&!j.pwprotect)g=getBG().lpmdec_acct(j.extra,!0,j,getBG().g_shares),(!g||0==g.length)&&console.log("searchinnotes: site aid="+j.aid+" FAILED TO DECRYPT"),l.push(g);j=l.join(" ");j=j.toLowerCase();c[h]=j}}return c}
function search_string_tokenize(a){var b=[];g_CNTsearch_string_tokenize++;if(!a)return b;if(-1==a.indexOf('"'))b=a.split(/\s+/);else{var c=[],c=a.split('"');for(a=0;a<c.length;a++)if(a%2)b.push(c[a]);else for(var f=[],f=c[a].split(/\s+/),g=0;g<f.length;g++)f[g]=f[g].replace(/^\s+/,""),f[g]=f[g].replace(/\s+$/,""),0<f[g].length&&b.push(f[g])}return b}
function search_it(a,b){g_CNTsearch_it++;for(var c="id"+a,f=1,g=0;g<b.length;g++)if(!(g_search_array[c]&&-1!=g_search_array[c].indexOf(b[g]))){f=0;break}return f}var populate_done=!1;
function populate(a,b){try{var c=getBG();g_CNTpopulate++;c.g_prompts.edit_sn_prompt||c.get_searchNotesPref();var f=$("#q").val(),g=0;a!=f&&($("#q").val(a),f=a,g=0);gLastSearch=a;gIconsLength=c.g_icons_length;gIdentity=c.g_identity;var f=[],h=[],l=[],j=[],r=[],u=0,w=[c.g_sites,c.g_securenotes],n;for(n in w)if(w.hasOwnProperty(n)){var y=w[n],q;for(q in y)if(y.hasOwnProperty(q)&&(u++,c.check_ident_aid(q))){for(var k=y[q],v=""!=k.group?k.group:"http://sn"==k.url?gs("Secure Notes"):g_xlat_none,v="_"+v;"\\"==
v[0];)v=v.substr(1);"undefined"==typeof f[v]&&(f[v]=[],h[h.length]=v,l[v]="undefined"==typeof k.aid?null:k.aid);f[v][f[v].length]=k;r[r.length]=k;"1"==k.fav&&(j[j.length]=k)}}for(q in c.g_applications)c.g_applications.hasOwnProperty(q)&&c.check_ident_appaid(q)&&(k=c.g_applications[q],v=""!=k.group?k.group:g_xlat_none,v="_"+v,"undefined"==typeof f[v]&&(f[v]=[],h[h.length]=v,l[v]="undefined"==typeof k.aid?null:k.aid),f[v][f[v].length]=k,r[r.length]=k,"1"==k.fav&&(j[j.length]=k));var w=0,m;for(m in c.g_pendings)c.g_pendings.hasOwnProperty(m)&&
(++w,k=c.g_pendings[m],""==a&&("undefined"==typeof f[g_xlat_pendingname]&&(f[g_xlat_pendingname]=[],h[h.length]=g_xlat_pendingname,l[g_xlat_pendingname]=null),f[g_xlat_pendingname][f[g_xlat_pendingname].length]=k));var H=h.length;h.sort(function(a,b){return"_Apps assigned to me"==a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});r.sort(function(a,b){return a.last_touch>b.last_touch?1:-1});var k=[],A=c.getClearRecentTime(),D=c.getRecentCount();if(""==a)for(m=0;k.length<D&&m<r.length;m++)"http://group"!=
r[r.length-m-1].url&&(r[r.length-m-1].last_touch<A||(k[k.length]=r[r.length-m-1]));k.length&&(h.unshift(g_xlat_runame),f[g_xlat_runame]=k);j.length&&(h.unshift(g_xlat_favorites),f[g_xlat_favorites]=j);A=[];""==a&&(A=getOpenedGroups());if(g_view==VIEWS.GRID)createGrid(getBG().g_sites);else{var z=[],D=[];resetgroupnames();event_handlers={};event_handlers_onmouseover={};event_handlers_onmouseout={};event_handlers_onclick={};styles={};for(m=0;m<h.length;m++){j=!1;if(""!=a||"undefined"!=typeof A[h[m]]||
1==H&&m==h.length-1)j=!0;var E="undefined"==typeof l[h[m]]?null:l[h[m]];"undefined"!=typeof h[m]&&addGroup(c,f,z,D,h[m],j,!1,A,E)}g_tree&&"undefined"!=typeof g_tree?($.tree.focused().settings.data.opts.static=z,$.tree.focused().refresh()):$(function(){var a={};a["static"]=z;var b={beforedelete:lpbeforedelete,beforemove:lpbeforemove,onmove:lponmove,check_move:lpcheck_move,onselect:lponselect};populate_done||(b.onrgtclk=lponrgtclk);$("#thetree").tree({callback:b,data:{type:"json",opts:a},rules:{multiple:"ctrl",
drag_copy:!1,use_max_children:!1,use_max_depth:!1},plugins:{hotkeys:{functions:{"return":function(){var a=$.tree.focused().selected;a&&(1==a.length&&(isNumber(a[0].id)||is_application(a[0].id)))&&ls(a[0].id)}}}}})});$(".shareimggroup").click(function(){var a=$(this).closest("li").get();a.length&&(a=getgroupnamefromid(a[0].id),0==a.indexOf("_")&&(a=a.substring(1)),0==a.indexOf("Shared-")?manageSharedFolder(a):shareFolder(a))});$(".toolsimg").click(function(){var a=$(this).closest("li").get();if(a.length){var a=
a[0],b=getgroupnamefromid(a.id);0==b.indexOf("_")&&(b=b.substring(1));openGroupMenu(a,b,t,event)}});$(".folder").mouseover(function(){sv(null,this)});$(".folder").mouseout(function(){hv(null,this)})}}catch(x){if("undefined"==typeof LPFromWebsite||"function"!=typeof LPFromWebsite.ipad){if(0<=x.message.indexOf("atob")&&-1==document.location.href.indexOf("retry")){document.location.href+="?retry=1";return}alert("populate_error:"+x)}}update_identity_popup();init_vault_search();populate_done=!0;a&&""!=
a&&SearchTree(g,b);for(m in event_handlers)document.getElementById(m)&&(document.getElementById(m).onclick=event_handlers[m]);for(m in event_handlers_onmouseover)for(var c=document.getElementsByName(m),p=0;p<c.length;p++)c[p].onmouseover=event_handlers_onmouseover[m];for(m in event_handlers_onmouseout){c=document.getElementsByName(m);for(p=0;p<c.length;p++)c[p].onmouseout=event_handlers_onmouseout[m]}for(m in event_handlers_onclick){c=document.getElementsByName(m);for(p=0;p<c.length;p++)c[p].onclick=
event_handlers_onclick[m]}for(m in styles)if(c=document.getElementById(m))for(p in styles[m])c.style[p]=styles[m][p]}
function lpbeforedelete(a){var b=getBG();if(1<($.tree.focused().selected_arr&&$.tree.focused().selected_arr.length)){for(var c="",f=[],g=0;g<$.tree.focused().selected_arr.length;g++){var h=getmoveid($.tree.focused().selected_arr[g]);h&&""!=h&&(c+=(""!=c?",":"")+h,f[f.length]=$.tree.focused().selected_arr[g])}b.deleteAid(c,window,!1,!1,function(){for(var a=0;a<f.length;a++)$.tree.focused().cut(f[a])});return!1}c=!1;is_application(a.id)||isNumber(a.id)?c=b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)}):
(c=getgroupnamefromid(a.id),c=b.deleteGroup(fix_group(c),window,function(){$.tree.focused().cut(a)}));return c}
function lpbeforemove(a,b){getBG().lpevent("v_dnd");for(var c="",f=b,c=0;f&&""==f.attr("id")&&100>c;)f=f.parent(),c++;if(99<c||!f)return!1;var g=f.attr("id");g.match(/launch_(nor|fav|rec)_\d+/)&&(g=g.substr(11));g.match(/accept2_(nor|fav|rec)_\d+/)&&(g=g.substr(12));var c="",h=getBG();if(is_application(g)||isNumber(g)){is_application(g)?(h=[h.g_applications],g=get_appaid(g)):h=[h.g_sites,h.g_securenotes];for(var l in h)if(h.hasOwnProperty(l)){var j=h[l],r;for(r in j)if(j.hasOwnProperty(r)){var u=
j[r];if(u.aid==g){if("1"==u.fav){j=f.parent();for(c=0;j&&""==j.attr("id")&&100>c;)j=j.parent(),c++;if(99>c&&j&&j.attr("id")==g_xlat_favorites){c=g_xlat_favorites;break}}c=u.group;break}}}}else c=getgroupnamefromid(g);if(!(""==c||c==g_xlat_runame||c==g_xlat_pendingname)){f=$.tree.focused().selected_arr;l="";for(r=0;r<f.length;r++)if(is_application(getmoveid(f[r]))||isNumber(getmoveid(f[r])))l+=(""==l?"":",")+getmoveid(f[r]);0==l.length&&(l=a.attr("id"));0!=l.length&&getBG().moveSelectedToGroup(c,l);
return!1}}function lponmove(){}function lpcheck_move(a){return 1<$.tree.focused().selected_arr.length?!0:a&&""!=a.attr("id")&&!is_application(a.attr("id"))&&!isNumber(a.attr("id"))?!1:!0}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}var g_groups={},g_groupindex=2E5,g_groupid={},g_groupnames={};function getgroupnamefromid(a,b){if("undefined"==typeof g_groups[a])return a;var c=g_groups[a];!b&&0==c.indexOf("_")&&(c=c.substring(1));return c}
function getrawgroupid(a){return"undefined"==typeof g_groupid[a]||null==g_groupid[a]?null:g_groupid[a]}function resetgroupnames(){g_groups={};g_groupindex=2E5;g_groupid={};g_groupnames={}}function getgroupid(a,b){var c="LpGrOuP"+g_groupindex;g_groups[c]=a;g_groupnames[a]=c;g_groupid[c]=b;++g_groupindex;return"LpGrOuP"+(g_groupindex-1)}function getgroupidfromname(a){return"undefined"==typeof g_groupnames[a]||null==g_groupnames[a]?null:g_groupnames[a]}var div_ids={};
function get_div_id(){for(;;){var a="div"+(new Date).getTime()+Math.random();if("undefined"==typeof div_ids[a])return div_ids[a]=!0,a}}var g_rootnodeid=null,g_lastnodeid=null;
function addGroup(a,b,c,f,g,h,l,j,r){var u="",w=g.indexOf("Shared-");if(g===g_xlat_favorites)u=" favorite";else if(g===g_xlat_runame)u=" recent";else if(0===w||1===w)u=" shared";for(;"\\"==g[0];)g=g.substr(1);for(var n=g.match(/^([^\\]*)\\(.*)$/),y=null!=n,q="",w=0;n&&!l;){var k=n[1],v=n[2],q=q+((""!=q?"\\":"")+k);"undefined"==typeof f[q]&&addGroup(a,b,c,f,q,h||"undefined"!=typeof j[q],!0,j,r);w++;n=v.match(/^([^\\]*)\\(.*)$/)}q=(""==q?"":"\\")+g;l=[];h=h?"open":"closed";j=b[g];"undefined"==typeof j&&
(j=[]);var m="nor_";g!=g_xlat_runame&&g!=g_xlat_pendingname?(j.sort(a.lp_sort_case_insensitive_name),g==g_xlat_favorites&&(m="fav_")):(j.sort(function(a,b){return a.last_touch>b.last_touch?-1:1}),g==g_xlat_runame&&(m="rec_"));for(var H=getcolvisibility("usernamecol"),A=getcolvisibility("ltnamecol"),D=navigator.userAgent.match("Gecko/"),z=1==g_showrows?"":"none",E=0;E<j.length;E++){var x=62+15*w;if(D||"undefined"!=typeof g_isopera&&g_isopera)x+=20;var p=j[E];if("http://group"!=p.url){n=k="";if("undefined"!=
typeof p.sharerusername)"undefined"!=typeof g_isopera&&g_isopera&&(k+="</a>"),b=get_div_id(),k+="<div class='actionmenu' id='"+b+"'><a href='#' id='accept_"+m+p.id+"' class='vaultlink'><img src='"+gLocalBaseUrl+"images/vaultaccept.png'/></a> | <a href='#' id='reject_"+m+p.id+"' class='vaultlink'><img src='"+gLocalBaseUrl+"images/vaultreject.png'/></a></div>",styles[b]={paddingRight:x+"px",display:z},event_handlers["accept_"+m+p.id]=function(){return accept(this.id.substring(11))},event_handlers["reject_"+
m+p.id]=function(){return reject(this.id.substring(11))},k+="<span class='clearboth'></span>",k+="<span><a href='#' id='accept2_"+m+p.id+"'>"+gs("Share offer from")+" "+of(a.hex2bin(p.sharerusername))+"</a></span>",event_handlers["accept2_"+m+p.id]=function(){return accept(this.id.substring(12))};else{var F=safclassdel=safclassshare="";if(g_issafari||g_isopera)F=" editsaf",safclassdel=" delsaf",safclassshare=" sharesaf";var n=get_record_id(p),C,B="<a href='#' id='share_"+m+n+"' class='vaultlink' title='"+
g_xlat_share+"'><span class='shareimg"+safclassshare+"'></span></a> ";event_handlers["share_"+m+n]=function(){return s(this.id.substring(10))};!a.LPISLOC&&!p.genpw&&("undefined"==typeof p.sharedfromaid||null==p.sharedfromaid||""==p.sharedfromaid||"0"==p.sharedfromaid||"null"==p.sharedfromaid)&&"undefined"==typeof p.sharefolderid&&!is_application(p)&&!1==a.g_hidesharing?C="":(C='<font class="hiddenfont">'+B+"</font>",B="");var G="";b="undefined"!=typeof p.sharedfromaid&&"0"!=p.sharedfromaid?p.sharedfromaid:
"";"undefined"!=typeof p.hasbeenshared&&1==p.hasbeenshared?(G="<p class='sharesubtext'><subtext id='sharesub_"+m+n+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+m+n]=function(){return s(this.id.substring(13))}):p.individualshare&&(""==b?(G="<p class='sharesubtext'><subtext id='sharesub_"+m+n+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+m+n]=function(){return s(this.id.substring(13))}):G="<p class='sharesubtext'>"+gs("shared with you")+"</p>");"undefined"!=typeof g_isopera&&
g_isopera&&(k+="</a>");b=get_div_id();k+="<div class='actionmenu' id='"+b+"'>"+C;styles[b]={paddingRight:x+"px",display:z};k+="<a href='#' id='chpw_"+m+n+"' class='vaultlink colhidden' title='"+g_xlat_chpw+"'><span class='chpwimg'></span></a> ";g_cpwbot&&p.pwch&&(event_handlers["chpw_"+m+n]=function(){e(this.id.substring(9),!0)});k+="<a href='#' id='edit_"+m+n+"' class='vaultlink' title='"+g_xlat_edit+"'><span class='editimg"+F+"'></span></a> ";event_handlers["edit_"+m+n]=function(){return e(this.id.substring(9))};
k+=B;k+="<a href='#' id='delete_"+m+n+"' class='vaultlink' title='"+g_xlat_delete+"'><span class='delimg"+safclassdel+"'></span></a></div>";event_handlers["delete_"+m+n]=function(){return d(this.id.substring(11))};k+="<span class='clearboth'></span>";k+="<span><a href='#' id='launch_"+m+n+"'>"+of(p.name)+"</a>"+G+"</span>";event_handlers["launch_"+m+n]=function(){return ls(this.id.substring(11))}}x="calc(5% + 10px)";F=H?"usercolvisible":"usercolhidden";C=A?"ltcolvisible":"ltcolhidden";B=of(a.getusernamefromacct(p));
""==B&&(B="&nbsp;");b=get_div_id();k+="<div id='"+b+"' class='"+F+"' name='usercol'>"+B+"</div>";styles[b]={cssFloat:"right",paddingRight:x,display:z};b=get_div_id();k+="<div id='"+b+"' class='"+C+"' name='ltcol'>"+("undefined"!=typeof p.last_touch?of(elapsedTime(p.last_touch)):"")+"</div>";styles[b]={cssFloat:"right",paddingRight:x,display:z};l[l.length]={data:{title:k,icon:a.geticonurlfromrecord(p)},attributes:{id:n,name:n}};event_handlers_onmouseover[n]=function(a){sv(a,this);return!1};event_handlers_onmouseout[n]=
function(a){hv(a,this);return!1};event_handlers_onclick[n]=function(a){lc(a,this);return!1}}}a=g;0==a.indexOf("_")&&(a=a.substring(1));j=30+15*w;k=g===g_xlat_favorites||g==g_xlat_runame||g==g_xlat_pendingname;b=get_div_id();k=k?"":"<div class='actionmenu' id='"+b+"'>"+("1"==getBG().g_enterpriseuser&&!is_personal_linked(a)?"<a href='#' title='"+g_xlat_share+"'><span class='shareimggroup'></span></a> ":"")+"<a href='#' title='"+gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";styles[b]=
{paddingRight:j+"px"};is_personal_linked(a)&&!y?(k+="<span class='boldspan' isgroup='1' >"+of(a)+" - "+of("Linked Personal Account")+"</span>",u=" linked"):k+="<span class='boldspan' isgroup='1' >"+of(a)+"</span>";f[g]=c.length;if(y){n=g.match(/^([^\\]*)\\(.*)$/);f=null;for(u=y=0;n;){k=n[1];v=n[2];if(0==y){for(q=c.length-1;0<=q;q--)if(c[q].group==k){f=c[q].children;break}u=0;y=1;if(!v.match(/^([^\\]*)\\(.*)$/))for(q=0;q<f.length;q++)if("undefined"==typeof f[q].group||f[q].group==k){u=q;break}}else{for(q=
n=0;q<f.length;q++)if("undefined"==typeof f[q].group){n=q-1;break}else if(f[q].group==k){n=q;break}f=f[n].children}n=v.match(/^([^\\]*)\\(.*)$/);if(!n)for(q=0;q<f.length;q++)if("undefined"==typeof f[q].group||f[q].group==k){u=q;break}else if(q==f.length-1){u=q+1;break}}n=getgroupid(g,r);j=30+15*w;b=get_div_id();k="<div class='actionmenu' id='"+b+"'>"+("1"==getBG().g_enterpriseuser&&!is_personal_linked(a)?"<a href='#' title='"+g_xlat_share+"'><span class='shareimggroup'></span></a> ":"")+"<a href='#' title='"+
gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";styles[b]={paddingRight:j+"px"};k+="<span class='boldspan' isgroup='1'>"+of(v)+"</span>";f.splice(u,0,{data:k,children:l,state:h,group:v,attributes:{"class":"folder",id:n}})}else 0==c.length&&(g_rootnodeid=g),g_lastnodeid=g,n=getgroupid(q,r),c[c.length]={data:k,children:l,state:h,group:g,attributes:{"class":"folder"+u,id:n}}}function getcolvisibility(a){return 0==localStorage.getItem(a)?!1:!0}
function setcolvisibility(a,b){localStorage_setItem(a,b)}
function matches(a,b,c){var f=b.toLowerCase();g_CNTmatches++;if(-1!=a.name.toLowerCase().indexOf(f)||(a.url&&-1!=a.url.toLowerCase().indexOf(f)||-1!=a.group.toLowerCase().indexOf(f)||a.unencryptedUsername&&-1!=a.unencryptedUsername.toLowerCase().indexOf(f))||is_application(a)&&(a.appname&&-1!=a.appname.toLowerCase().indexOf(f)||-1!=getusernamefromacct(a).toLowerCase().indexOf(f)))return!0;if(c&&"undefined"!=typeof a.extra&&0<a.extra.length&&("undefined"==typeof a.url||"http://group"!=a.url))if(c=
getBG().lpmdec_acct(a.extra,!0,a,getBG().g_shares),g_CNTmatches_decrypt++,-1!=c.toLowerCase().indexOf(f))return!0;return"has:attachment"==b&&"undefined"!=typeof a.attachid&&null!=a.attachid&&0!=a.attachid?!0:!1}var g_cachedOpenGroups=null;
function getOpenedGroups(){var a=getBG(),b=[],c="";if("undefined"==typeof LPFromWebsite){if("undefined"==typeof localStorage)return b;g_cachedOpenGroups&&g_cachedOpenGroups.length?c=g_cachedOpenGroups:(c=localStorage.getItem(a.db_prepend(a.g_username_hash+".savedtree")),g_cachedOpenGroups=c=a.dec(c))}else c=LPFromWebsite.readopengroups();if(!c||""==c)return b;a=c.split(",");for(c=0;c<a.length;c++)b[a[c].replace("%2C",",")]=1;return b}
function saveGroupState(){var a=getBG();if(!massoperation&&a.lploggedin){var b="",c=$("#thetree").find(".open");$.each(c,function(a,c){var h=getgroupnamefromid(c.id,!0);h.replace(",","%2C");b+=h+","});"undefined"==typeof LPFromWebsite?"undefined"!=typeof localStorage&&g_cachedOpenGroups!=b&&(g_cachedOpenGroups=b,c=a.enc(b),localStorage_setItem(a.db_prepend(a.g_username_hash+".savedtree"),c)):LPFromWebsite.saveopengroups(b)}}
function lc(a,b){$.tree.focused().select_branch(b,a.ctrlKey|a.metaKey,a.shiftKey)}function sv(a,b){$(b).children(".actionmenu").find("span").each(function(){$(this).css("opacity","1.0")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="inline-block")}
function hv(a,b){$(b).children(".actionmenu").find("span").each(function(){$(this).css("opacity","0.2")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="none")}function lponopen(){saveGroupState()}function lponclose(){saveGroupState()}function lponselect(){document.getElementById("q").blur()}var g_lastpop=0;
function lponrgtclk(a,b,c){var f=$.tree.focused().selected_arr&&$.tree.focused().selected_arr.length;1==f&&a!==b.selected&&b.select_branch(a);getBG().lpevent("v_rgt");var g=(new Date).getTime();if(!(g_lastpop>g-500)){g_lastpop=g;if(1<f){for(var h="",l=[],j=!1,r=!1,f=0;f<$.tree.focused().selected_arr.length;f++)if((g=getmoveid($.tree.focused().selected_arr[f]))&&""!=g)is_application(g)&&(j=!0),get_record(g)&&"undefined"!=typeof get_record(g).sharefolderid&&(r=!0),h+=(""!=h?",":"")+g,l[l.length]=$.tree.focused().selected_arr[f];
setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};c[gs("Move Selected to Group")]=function(){b.lpevent("v_multmov");openMoveGroup(a)};!j&&!r&&(c[gs("Share Selected")]=function(){b.lpevent("v_mults");s(h)});c[gs("Delete Selected")]=function(){b.lpevent("v_multd");b.deleteAid(h,window,!1,!1,function(){for(var a=0;a<l.length;a++)$.tree.focused().cut(l[a])})};return[c]},{theme:"vista"}).show(b,c)},100)}else if("undefined"!=typeof a)if(""!=a.id&&!is_application(a.id)&&!isNumber(a.id)){f=
getgroupnamefromid(a.id);0==f.indexOf("_")&&(f=f.substring(1));for(var g=!1,u=a;u.parentNode&&u.parentNode!=u;)if(u=u.parentNode,"thetree"==u.id){g=!0;break}if(!g)return;openGroupMenu(a,f,b,c);c.preventDefault()}else""!=a.id&&(is_application(a.id)||isNumber(a.id))&&setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};if("undefined"!=typeof getBG().g_sites[a.id]||is_application(a.id)){if("undefined"==typeof g_issafari&&"undefined"==typeof g_isopera&&"undefined"==typeof g_ismaxthon&&
"undefined"==typeof g_isfirefoxsdk||"function"==typeof b.can_copy_to_clipboard&&b.can_copy_to_clipboard()||"undefined"!=typeof g_is_safari)c[gs("Copy Username")]=function(){b.copyusername(a.id)},c[gs("Copy Password")]=function(){b.copypassword(a.id)},c[gs("Copy URL")]=function(){b.copyurl(a.id)}}else if("undefined"!=typeof getBG().g_securenotes[a.id]){var f=getBG().g_securenotes[a.id],g="undefined"!=typeof f.notetype?f.notetype:"";"undefined"!=typeof sntemplates[g]&&"undefined"!=typeof sntemplates[g].Username&&
(c[gs("Copy Username")]=function(){b.copyusername(a.id)});var f=getBG().lpmdec_acct(f.extra,!0,f,getBG().g_shares),h;h=0|-1<f.indexOf("Wi-Fi Password");h|=-1<f.indexOf("Email Account");h=(h|=-1<f.indexOf("Server"))&&-1<f.indexOf("Password");if("undefined"!=typeof sntemplates[g]&&"undefined"!=typeof sntemplates[g].Password||h)c[gs("Copy Password")]=function(){b.copypassword(a.id)}}c[gs("Move to Group")]=function(){b.lpevent("v_mov");openMoveGroup(a)};c[gs("Move to Sub-Group")]=function(){b.lpevent("v_msub");
openMoveGroup(a,!0)};g=get_record(a.id);if(!is_application(a.id)&&get_record(a.id)&&"undefined"==typeof get_record(a.id).sharefolderid&&("undefined"==typeof g.sharedfromaid||null==g.sharedfromaid||""==g.sharedfromaid||"0"==g.sharedfromaid||"null"==g.sharedfromaid))c[gs("Share")]=function(){s(a.id)};c[gs("Delete")]=function(){b.lpevent("v_rgtd");b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)})};c[gs("Edit")]=function(){b.lpevent("v_rgte");b.editAid(a.id,window)};"undefined"!=typeof getBG().g_sites[a.id]&&
(c[gs("Go to URL")]=function(){b.lpevent("v_g2");b.gotourl(a.id,null)});return[c]},{theme:"vista"}).show(b,c)},100);c.preventDefault()}}var lastqstr="";
function SearchTree(a,b,c){g_CNTsearch_tree++;var f=!1;0<document.location.href.indexOf("cmd=viewcreditmon")&&1!=g_autoselectcredmontab?(ontabchange(document.getElementById("credmon")),g_autoselectcredmontab=1):"sites"!=g_activetab.id&&(f=!0);var g=$("#q").val(),h=!1;if(a||g!=lastqstr)f&&!b&&(ontabchange(document.getElementById("sites")),h=!0),gLastSearch=lastqstr=g,massoperation=!0,""==g?c||clearTree():$.tree.focused().search(g),massoperation=!1;f&&!h&&setTimeout(function(){ontabchange(g_activetab)},
0);document.getElementById("searchx").src=""==g?gLocalBaseUrl+"images/search.png":gLocalBaseUrl+"images/cancel.png"}function ls(a){var b=getBG();b.lpevent("v_ls");b.launch(a);return!1}function cu(a){var b=getBG();b.lpevent("v_cu");b.copyusername(a);return!1}function cp(a){var b=getBG();b.lpevent("v_cp");b.copypassword(a);return!1}function curl(a){var b=getBG();b.lpevent("v_curl");b.copyurl(a);return!1}function e(a,b){var c=getBG();c.lpevent("v_e");c.editAid(a,window,null,b);return!1}
function d(a){var b=getBG();b.lpevent("v_d");b.deleteAid(a,window);return!1}function is_protected(a){"string"==typeof a&&(a=a.split(","));for(var b=0;b<a.length;b++){var c=get_record(a[b]);if(c&&1==c.pwprotect)return!0}return!1}function s(a){getBG().lpevent("v_s");callServerFunction("share",a);return!1}
function MoveFocus(a){if(40==a.keyCode||34==a.keyCode||38==a.keyCode||33==a.keyCode)a=38==a.keyCode||33==a.keyCode?getgroupidfromname(g_lastnodeid):getgroupidfromname(g_rootnodeid),$.tree.focused().select_branch("#"+a),document.getElementById("q").blur()}function clearTree(){g_CNTclear_tree++;populate("");document.getElementById("searchx").src=gLocalBaseUrl+"images/search.png";document.getElementById("q").value=""}var massoperation=!1;
function expandall(){if(!getBG().lploggedin)return!1;massoperation=!0;$.tree.focused().open_all();massoperation=!1;saveGroupState()}function collapseall(){if(!getBG().lploggedin)return!1;massoperation=!0;$.tree.focused().close_all();massoperation=!1;saveGroupState()}function creategroup(){var a=getBG();a.lploggedin&&(a.lpevent("v_cg"),openCreateGroup(null))}
function showformfill(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a=getBG(),b={},c;for(c in a.g_formfills)a.g_formfills.hasOwnProperty(c)&&a.check_ident_ffid(a.g_formfills[c].ffid)&&(b[of(a.g_formfills[c].decprofilename)]=function(a){editff(get_innerText(a))});a={};a[gs("Add Profile")]=function(){getBG().addprofile()};a[gs("Add Credit Card")]=function(){getBG().addcreditcard()};return[b,"context-menu-separator",a]},{theme:"vista"}).show(a,
b)},0);return!1}function editff(a){var b=getBG();a=$.trim(a);for(var c in b.g_formfills)if(b.g_formfills.hasOwnProperty(c)&&a==$.trim(b.g_formfills[c].decprofilename)){b.editprofile(b.g_formfills[c].ffid);break}}
function showmoremenu(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a={};gHidePreferences||(a[gs("Preferences")]=function(){getBG().openprefs()});getBG().LPISLOC||(a[gs("History")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&openhistory=1")},a[gs("Show Deleted Sites")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&showdeleted=1")});if(!getBG().LPISLOC||!getBG().LPISUPEK)a[gs("Change Password")]=
function(){getBG().unlock_plug2web();getBG().changemasterpassword()};a[gs("Forums")]=function(){getBG().openURL("http://forums.lastpass.com")};a[gs("Blog")]=function(){getBG().openURL("http://blog.lastpass.com")};getBG().g_isadmin&&(a[gs("Admin Tools")]=function(){getBG().openURL("https://rodan.lastpass.com/admintools/")});return[a]},{theme:"vista"}).show(a,b)},0);return!1}function addsecurenote(){getBG().lpevent("v_addn");getBG().openaddsecurenote();return!1}
function logoff(){if(!getBG().lploggedin)return!1;finish_vault_search();getBG().lpevent("v_off");saveGroupState();getBG().loggedOut(!1,"homelocal2");return!1}function accept(a){getBG().lpevent("v_apt");callServerFunction("acceptshare",a)}function reject(a){getBG().lpevent("v_rjt");callServerFunction("rejectshare",a)}function login(){getBG().lpevent("v_lgn");getBG().open_login(!0);return!1}
function changeidentity(a,b){("undefined"==typeof b||!0==b)&&closepopup();getBG();getBG().lpevent("v_cid");getBG().switch_identity(a);document.getElementById("identity").value=getBG().g_identity;setusernametext(getBG().g_username);closepopup()}var gMoveSelected=null;
function openMoveGroup(a,b,c){if(addedjqueryui){gMoveSelected=$.tree.focused().selected_arr;if("undefined"==typeof gMoveSelected||0==gMoveSelected.length)gMoveSelected=Array(a);var f=getBG(),g=[],h=[],l=[f.g_sites,f.g_securenotes,f.g_applications],j="",r;for(r in l)if(l.hasOwnProperty(r)){var u=l[r],w;for(w in u)if(u.hasOwnProperty(w)){var n=u[w];if(gMoveSelected&&(1==gMoveSelected.length&&getmoveid(gMoveSelected[0])==get_record_id(n))&&(j=n.group,b)){""!=n.group&&(g[g.length]=n.group);break}n=""!=
n.group?n.group:gs("(none)");"undefined"!=typeof n&&"undefined"==typeof h[n]&&(h[n]="1",g[g.length]=n)}}g.sort(function(a,b){return"_Apps assigned to me"==a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});h=!1;""==j&&(1==gMoveSelected.length&&!isNumber(getmoveid(gMoveSelected[0])))&&(j=getmoveid(gMoveSelected[0]),h=!0);l=-1!=j.indexOf("\\")&&0<j.substring(j.indexOf("\\")+1).length;if(h&&0===j.indexOf("Shared-")&&!l){if(g=void 0,c){for(i in f.g_sites)if(f.g_sites[i].group==j){g=
f.g_sites[i].aid;break}callServerFunction("renamesharedfolder",g)}}else document.getElementById("grpsel").value="",repopulate_combo("grpsel",g),document.getElementById("dialog").title=gs("Change Group Name"),document.getElementById("dialogtext").innerHTML=gs("Select or enter a new group name"),document.getElementById("dialoggrpinp").style.display="none",document.getElementById("dialoggrpsel").style.display="block",document.getElementById("dosubgroup").value="undefined"!=typeof b&&b?"1":"0",1==gMoveSelected.length&&
(b?document.getElementById("dialogtext").innerHTML+="<br/><br/>"+gs("Group will be created or currently exists under")+": <br/>"+of(j):document.getElementById("grpsel").value=j),$("#dialog").dialog("destroy"),$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,dragStop:function(){var a=document.getElementById("grpsel_combo");a&&"block"==a.style.display&&realShowCombo()},close:function(){var a=document.getElementById("grpsel_combo");a&&"block"==a.style.display&&
close_combo("grpsel")},buttons:{Change:function(){var a=1==gMoveSelected.length?getmoveid(gMoveSelected[0]):"";if(1==gMoveSelected.length&&""!=a&&!is_application(a)&&!isNumber(a))getBG().renameGroup(fix_group(a),fix_group(document.getElementById("grpsel").value));else{for(var b="",c=0;c<gMoveSelected.length;c++)if(a=getmoveid(gMoveSelected[c]),is_application(a)||isNumber(a))b+=(""==b?"":",")+a;if(0==b.length)return;a=document.getElementById("grpsel").value;1==gMoveSelected.length&&"1"==document.getElementById("dosubgroup").value&&
a!=j&&0!=a.indexOf(j+"\\")&&(a=j+"\\"+a);getBG().moveSelectedToGroup(a,b)}populate(gLastSearch);$(this).dialog("close")},Close:function(){$(this).dialog("close")}}}),$("#dialog").dialog("open"),$("#grpsel").click()}else addJqueryUI(),setTimeout(function(){openMoveGroup(a,b,c)},250)}var selected_global;
function openCreateGroup(a){addedjqueryui||(addJqueryUI(),setTimeout(function(){openCreateGroup(a)},250));selected_global=a;getBG().lpevent("v_cg");document.getElementById("dialog").title=gs("Group Name");document.getElementById("dialogtext").innerHTML=gs("Group Name");document.getElementById("dialoggrpinp").style.display="block";document.getElementById("grpinp").value="";document.getElementById("dialoggrpsel").style.display="none";"function"==typeof $("#dialog").dialog&&($("#dialog").dialog("destroy"),
$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,buttons:{OK:function(){var a=document.getElementById("grpinp").value;for(null!=selected_global&&(a=fix_group(getmoveid(selected_global))+"\\"+a);"\\"==a[0];)a=a.substr(1);if(a==gs("favorites")||a==g_xlat_runame||a==g_xlat_pendingname)alert(gs("That group already exists."));else if(null==selected_global&&0==a.indexOf("Shared-"))alert(gs("Sorry - group names starting with 'Shared-' are created by LastPass to indicate groups shared with other people. Please use a different name."));
else{var c=getBG(),f=[c.g_sites,c.g_securenotes,c.g_applications],g;for(g in f)if(f.hasOwnProperty(g)){var h=f[g],l;for(l in h)if(h.hasOwnProperty(l)&&h[l].group==a){alert(gs("That group already exists."));return}}c.addEmptyGroup(a);populate(gLastSearch);$(this).dialog("close")}},Close:function(){$(this).dialog("close")}}}),"function"==typeof $("#dialog").dialog&&$("#dialog").dialog("open"));$("#grpinp").click()}
function getmoveid(a){var b="",b="undefined"!=typeof a.id?getgroupnamefromid(a.id,!0):getgroupnamefromid(a.attr("id"),!0);0==b.indexOf("_")&&(b=b.substring(1));return b}function getacct(a){return get_record(a)}function getDragHTMLForNode(a){var b=a;for(a=0;b&&""==b.attr("id")&&100>a;)b=b.parent(),a++;a=getBG();b=b.attr("id");return(b=getacct(b))?"<div><img src='"+a.geticonurlfromrecord(b)+"' />&nbsp;<span>"+of(b.name)+"</span></div>":""}
function getDragHTML(a){var b="<div id='jstree-dragged' class='tree default'>";if(null==a){a=$.tree.focused().selected_arr;for(var c=0;c<a.length;c++)b+=getDragHTMLForNode(a[c])}else b+=getDragHTMLForNode(a);return b+"</div>"}var togglestate=0;
function toggleUserCol(){var a=getcolvisibility("usernamecol"),b=getcolvisibility("ltnamecol"),c="usercol",f="usernamecol",g="usercolhidden",h="usercolvisible",l=a;1==togglestate%2?(c="ltcol",f="ltnamecol",g="ltcolhidden",h="ltcolvisible",l=b):document.getElementById("ltcol").style.paddingRight=!a?"5%":"calc(5% + 20px)";togglestate++;a=document.getElementsByName(c);for(b=0;b<a.length;b++)a[b].className=l?g:h,0==b&&setcolvisibility(f,l?"0":"1")}
function openinparent(a,b){0!=a.indexOf("http")&&(a=g_urlprefix+a);a+="?";for(var c in b)b.hasOwnProperty(c)&&(a+="&"+en(c)+"="+en(b[c]));window.open(a)}function showpopup(){getBG().lploggedin?document.getElementById("lppopup").style.display="block":login()}document.addEventListener("click",closepopup,!0);
function closepopup(a){if("block"==document.getElementById("lppopup").style.display&&(!a||!a.target||"person"!=a.target.id&&"identity"!=a.target.id&&"lpusername"!=a.target.id))document.getElementById("lppopup").style.display="none"}var translations=[];translations.DeleteSiteConfirm=gs("Are you sure you want to delete this site?");translations.DeleteSite=gs("Delete Site?");translations.DeleteIdentityConfirm=gs("Are you sure you want to delete this identity?");translations.DeleteIdentity=gs("Delete Identity?");
translations["Invalid Password."]=gs("Invalid Password.");translations["Add Site"]=gs("Add Site");translations["Add Profile"]=gs("Add Profile");translations["Add Identity"]=gs("Add Identity");this.updated_enc=function(){return!0};var g_waitbox=null;
this.show_waitbox=function(a,b){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy());var c=gs("Submitting...");"undefined"!=typeof a&&null!=a&&!0==a?c=gs("LastPass must reencrypt all of your data because of a key change.")+"<br/><br/>"+gs("This may take a while...")+"<br/><br/>"+gs("Please keep this page open until the operation completes.")+'<br/><br/><div id="changepw_progress" class="width300div"></div>':"undefined"!=typeof b&&(b&&""!=b)&&(c=b);b=gs("Please Wait...");var f=Math.min(750,200+4*c.length);
g_waitbox=new Ext.Window({closable:!1,width:f,autoHeight:!0,layout:"fit",modal:!0,title:b,bodyStyle:"padding: 20px",id:"waitbox",html:"<br/><br/><b>"+c+"</b><br/><br/>"});g_waitbox.show()};this.hide_waitbox=function(){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy(),g_waitbox=null)};this.populateff=function(a,b){for(var c=getBG(),f=convert_object_to_array(c.g_formfills),g=[],h=0;h<f.length;h++){var l=f[h];c.check_ident_ffid(l.ffid)&&g.push(l)}populateffcommon(g,a,b)};
this.openff=function(a){getBG().lpevent("v_off");getBG().editprofile(a)};this.delff=function(a){confirm(gs("Are you sure you would like to delete this form fill profile?"))&&(getBG().lpevent("v_dff"),getBG().deleteformfill(a))};
this.populateident=function(a){var b=convert_object_to_array(getBG().g_identities);if(b.length){if(document.getElementById("identiframe")){var c=document.getElementById("identpane");c.removeChild(document.getElementById("identiframe"))}populateidentcommon(b,a)}else if(!document.getElementById("identiframe")){for(c=document.getElementById("identpane");c.children.length;)c.removeChild(c.children[0]);a=document.createElement("iframe");a.id="identiframe";a.className="overviewiframe";a.src=getpartnerurl("ident_overview.php");
c.appendChild(a)}};this.openident=function(a){getBG().lpevent("v_oid");callServerFunction("identity",a);return!1};this.delident=function(a){getBG().lpevent("v_did");confirm(gs("Are you sure you want to delete this identity?"))&&callServerFunction("deleteidentity",a,getBG().g_token);return!1};
this.populateshares_remote=function(){cleartab("sharepane");var a=document.getElementById("sharepane");if(!document.getElementById("shareiframe")){getBG().unlock_plug2web();var b=document.createElement("iframe");b.id="shareiframe";b.className="overviewiframe";b.src=getpartnerurl("share_overview.php?extension=1");a.appendChild(b)}};
this.populatealerts=function(){cleartab("credmonpane");var a=document.getElementById("credmonpane");if(!document.getElementById("credmoniframe")){var b=document.createElement("iframe");b.id="credmoniframe";b.className="overviewiframe";b.src=getpartnerurl("credmon_overview.php");a.appendChild(b)}};this.cleartab=function(a){for(a=document.getElementById(a);a&&a.children.length;)a.removeChild(a.children[0])};this.refreshsites=function(){getBG().refreshsites()};
this.website_event=function(){var a=document.getElementById("eventtype").value;lpdbg("vault","new vault got website event: "+a);var b={cmd:a,url:g_urlprefix,callback:website_event_callback};switch(a){case "refresh":b.from=document.getElementById("eventdata1").value;b.type=document.getElementById("eventdata2").value;break;case "logoff":break;case "clearcache":break;case "keyweb2plug":b.cmd="web2plug";b.key=document.getElementById("eventdata1").value;b.username=document.getElementById("eventdata2").value;
b.rsa=document.getElementById("eventdata3").value;break;case "checkmultifactorsupport":b.type=document.getElementById("eventdata1").value;break;case "setupsinglefactor":b.type=document.getElementById("eventdata1").value;b.username=document.getElementById("eventdata2").value;b.password=document.getElementById("eventdata3").value;b.silent=document.getElementById("eventdata5").value;"1"!=document.getElementById("eventdata5").value&&g_websiteeventtarget&&g_websiteeventtarget.source.postMessage({cmd:a,
result:"working"},g_websiteeventtarget.origin);break;case "rsadecrypt":b.sharerpublickeyhex=document.getElementById("eventdata1").value;b.sharekeyenchexsig=document.getElementById("eventdata2").value;b.sharekeyenchex=document.getElementById("eventdata3").value;b.sharekeyhex=document.getElementById("eventdata4").value;break;case "request_native_messaging":break;default:console.error("got unsupported website event on new vault: "+a);return}getBG().processCS(null,b,null)};
this.website_event_callback=function(a){lpdbg("vault","new vault got website event callback: "+a.cmd);"checkmultifactorsupport"==a.cmd?(document.getElementById("eventdata4").value=a.type,document.getElementById("eventdata3").value=a.result,g_websiteeventtarget&&g_websiteeventtarget.source.postMessage(a,g_websiteeventtarget.origin)):"setupsinglefactor"==a.cmd?(document.getElementById("eventdata4").value=a.result,g_websiteeventtarget&&g_websiteeventtarget.source.postMessage(a,g_websiteeventtarget.origin)):
"ipcgotdata"==a.cmd&&g_ipctarget.source.postMessage(a,g_ipctarget.origin)};var g_loaded=g_haspluginrsa=!1,g_func=null;this.callFunction=function(a){getBG().lploggedin&&(g_loaded?a():(g_func=a,a=document.createElement("link"),a.rel="stylesheet",a.type="text/css",a.href=g_urlprefix+"m.php/default_ext",document.body.appendChild(getpartnerurl(a)),a=document.createElement("script"),a.src=g_urlprefix+getpartnerurl("m.php/localvault_async?rand="+Math.floor(1E3*Math.random())),document.body.appendChild(a)))};
this.doneloadingexternaljs=function(){g_loaded=!0;g_func&&g_func();g_func=null};this.openaddbytab=function(){if(getBG().lploggedin)return"ident"==g_activetab.id?callServerFunction("identity",""):"ff"==g_activetab.id||"credmon"==g_activetab.id?getBG().addprofile():getBG().openaddsite(),!1};this.opencreditmondash=function(a,b){if(getBG().lploggedin)return a?callServerFunction("opencreditmondash",b):callServerFunction("opencreditmondashnoalert",b),!1};function togglerows(){}
var g_ipctarget=null,g_websiteeventtarget=null;
window.addEventListener("message",function(a){if(!("undefined"==typeof getBG().base_url||0!=getBG().base_url.indexOf(a.origin))){var b=a.data+"";if("addprofile"==b||"addidentity"==b)openaddbytab();else if(0<=b.indexOf("showcredmondash_"))a=b.substr(16),opencreditmondash(!0,a);else if(0<=b.indexOf("showcredmondashnoalert_"))a=b.substr(23),opencreditmondash(!1,a);else if("object"==typeof a.data)if("getdata"==a.data.msg)0==a.data.url.indexOf(getBG().base_url)&&(g_ipctarget=a,getBG().processCS(null,{cmd:"ipcgetdata",
url:a.data.url,callback:website_event_callback},null));else if("refreshsites"==a.data.msg)getBG().refreshsites();else if("closeiframe"==a.data.msg)a=document.body,b=document.getElementById("__serveriframe"),a&&b&&a.removeChild(b);else if("websiteevent"==a.data.msg)g_websiteeventtarget=a,document.getElementById("eventtype").value=a.data.eventtype,document.getElementById("eventdata1").value=a.data.eventdata1,document.getElementById("eventdata2").value=a.data.eventdata2,document.getElementById("eventdata3").value=
a.data.eventdata3,document.getElementById("eventdata4").value=a.data.eventdata4,document.getElementById("eventdata5").value=a.data.eventdata5,website_event();else if(0==a.data.msg.indexOf("sharefolder_")&&(b=a.data.msg.match(/^sharefolder_([^_]+)_(.*)$/)))a=b[1],b=b[2],"undefined"!=typeof share_folder_group&&share_folder_group==b&&(share_folder_id=a,getBG().set_share_folder_id(a))}},!1);
function callServerFunction(a,b,c,f){var g=getBG();if(g.lploggedin){g.unlock_plug2web();var h=document,l=!1;if("share"==a||"acceptshare"==a||"rejectshare"==a){if(l=g.g_prompts.edit_site_prompt||g.g_prompts.edit_sn_prompt,!l&&"share"==a)for(var j=b.split(","),r=0;r<j.length;r++){var u=get_record(j[r]);if(u&&u.pwprotect){l=!0;break}}}else if("identity"==a||"deleteidentity"==a){if(l=g.g_prompts.switch_identity_prompt,!l&&""!=b){j=convert_object_to_array(g.g_identities);for(r=0;r<j.length;++r)if(j[r].iid==
b&&j[r].pw_prompt){l=!0;break}}}else if("opencreditmondash"==a||"opencreditmondashnoalert"==a)l=!1;if(l&&!f)g.security_prompt(function(){callServerFunction(a,b,c,!0)});else{f=h.body;h=h.createElement("iframe");h.type="content";g=1E3*Math.random();g=g_urlprefix+"acctsiframe.php?rand="+g+"&command="+encodeURIComponent(a);b&&(g+="&commandid="+encodeURIComponent(b));c&&(g+="&commandtoken="+encodeURIComponent(c));g+="&version="+encodeURIComponent(lpversion);h.setAttribute("src",getpartnerurl(g));h.id=
"__serveriframe";h.style.position="absolute";h.style.top=h.style.left="0px";try{var w=f.ownerDocument.defaultView.getComputedStyle(f,"");h.style.width=w.width;h.style.height=w.height}catch(n){}f.appendChild(h)}}}function manageSharedFolder(a){var b=getBG(),c=a.indexOf("\\");-1!=c&&(a=a.substring(0,c));for(var f in b.g_shares)if(b.g_shares[f].decsharename==a){callServerFunction("sharedfolders",b.g_shares[f].id);break}}
function shareFolder(a){share_folder_id="";getBG().set_share_folder_id("");share_folder_group=a;getBG().set_share_folder_group(a);callServerFunction("sharefolder",a)}function sendToManageSharedFolders(){alert("Please delete Shared Folders using the Manage Shared Folders link")}
function openGroupMenu(a,b,c,f){var g=getrawgroupid(a.id);setTimeout(function(){$.contextMenu.create(function(){var c=getBG(),f={};b!=g_xlat_favorites&&(b!=g_xlat_runame&&b!=g_xlat_pendingname)&&(0==b.indexOf("Shared-")?f[gs("Manage Shared Folder")]=function(){manageSharedFolder(b)}:"1"==getBG().g_enterpriseuser&&!is_personal_linked(b)&&(f[gs("Share Folder")]=function(){shareFolder(b)}),f[gs("Rename Group")]=function(){c.lpevent("v_ren");openMoveGroup(a,void 0,!0)},f[gs("Delete Group")]=function(){0==
b.indexOf("Shared-")&&-1==b.indexOf("\\")?(callServerFunction("sharedfolders"),sendToManageSharedFolders()):(c.lpevent("v_dg"),c.deleteGroup(fix_group(b),window,function(){$.tree.focused().cut(a)},"homelocal2.html B",0,g))},f[gs("Create Sub-Group")]=function(){c.lpevent("v_csub");openCreateGroup(a)});f[gs("Open All")]=function(){c.openall(b)};return[f]},{theme:"vista"}).show(c,f)},0)}
function createGrid(a){for(var b in a)if(a.hasOwnProperty(b)){var c=get_record(b);addGridBox(c.aid,c.name,getusernamefromacct(c))}}
function addGridBox(a,b,c){a=gLocalBaseUrl+"images/logos/"+"adobe.com.png dropbox.com.png microsoft.com.png windows.com.png adobecreativecloud.com.png ebay.com.png pandora.com.png wordpress.com.png amazon.com.png evernote.com.png paypal.com.png xmarks.com.png americanexpress.com.png facebook.com.png pinterest.com.png yahoo.com.png apple.com.png godaddy.com.png skype.com.png att.com.png google.com.png twitter.com.png chase.com.png linkedin.com.png verizonwireless.com.png".split(" ")[Math.floor(25*Math.random())];
c||(c="");b="<div class='tile'><img class='tlogo' src='"+a+"'/><div><p class='name'>"+of(b)+"</p><p class='usernamename'>"+of(c)+"</p><img class='more' src='"+gLocalBaseUrl+"images/lock.png'/></div></div>";$(b).appendTo($("#thegrid"))}var I_SHOW=!0,I_HIDE=!1;function refresh_ident_actions(){var a=getBG();a&&convert_object_to_array(a.g_identities).length&&showhide_ident_actions(I_SHOW)}
function showhide_ident_actions(a){getBG();a==I_SHOW?(document.getElementById("ident").style.display="table-cell",document.getElementById("lpidentities").style.display="block"):(document.getElementById("ident").style.display="none",document.getElementById("lpidentities").style.display="none")};
