function lpPutUserPref(b,c){"undefined"==typeof g_userprefs&&(g_userprefs=getBG().g_userprefs);if("undefined"==typeof g_userprefs[b]||g_userprefs[b]!=c)g_userprefs_changed[b]=!0;g_userprefs[b]=c}function lpPutGblPref(b,c){"undefined"==typeof g_gblprefs&&(g_gblprefs=getBG().g_gblprefs);if("undefined"==typeof g_gblprefs[b]||g_gblprefs[b]!=c)g_gblprefs_changed[b]=!0;g_gblprefs[b]=c}
function lpGetPref(b,c){"undefined"==typeof g_userprefs&&(g_userprefs=getBG().g_userprefs);if("undefined"!=typeof g_userprefs&&"undefined"!=typeof g_userprefs[b])return g_userprefs[b];"undefined"==typeof g_gblprefs&&(g_gblprefs=getBG().g_gblprefs);return"undefined"!=typeof g_gblprefs&&"undefined"!=typeof g_gblprefs[b]?g_gblprefs[b]:c}
function dodefault(){var b=get_innertext(document.getElementById("default"));0<=b.indexOf("General")?(document.getElementById("logoffWhenCloseBrowserVal").value=0,document.getElementById("logoffWhenCloseBrowser").checked=!1,document.getElementById("idleLogoffVal").value="",document.getElementById("idleLogoffEnabled").checked=!1,document.getElementById("openpref").value="tabs",document.getElementById("highlightFields").checked=!0,document.getElementById("automaticallyFill").checked=!0,document.getElementById("showvault").checked=
!1,document.getElementById("showAcctsInGroups").checked=!0,document.getElementById("hideContextMenus").checked=!1,document.getElementById("defaultffid").value=0,document.getElementById("donotoverwritefilledfields").checked=!1):0<=b.indexOf("Notifications")?(document.getElementById("showNotifications").checked=!0,document.getElementById("showGenerateNotifications").checked=!1,document.getElementById("showFormFillNotifications").checked=!1,document.getElementById("showNotificationsAfterClick").checked=
!1,document.getElementById("showFillNotificationBar").checked=!1,document.getElementById("showSaveNotificationBar").checked=!0,document.getElementById("showSaveSiteNotifications").checked=!1,document.getElementById("showChangeNotificationBar").checked=!0,document.getElementById("showmatchingbadge").checked=!0,document.getElementById("usepopupfill").checked=!0):0<=b.indexOf("Hotkeys")?(document.getElementById("generateHk").value="Alt+G",document.getElementById("recheckHk").value="Alt+I",document.getElementById("searchHk").value=
"Alt+W",document.getElementById("nextHk").value="Alt+Page Up",document.getElementById("prevHk").value="Alt+Page Down",document.getElementById("submitHk").value="",document.getElementById("homeHk").value="Ctrl+Alt+H",document.getElementById("saveallHk").value="",document.getElementById("logoffHk").value="",document.getElementById("defaultffidHk").value=""):0<=b.indexOf("Advanced")?(document.getElementById("autoautoEnabled").checked=!0,document.getElementById("autoautoVal").value="25",document.getElementById("warninsecureforms").checked=
!1,document.getElementById("dontfillautocompleteoff").checked=!1,document.getElementById("pollServerEnabled").checked=!1,document.getElementById("pollServerVal").value="15",document.getElementById("recentUsed").checked=!0,document.getElementById("recentUsedCount").value="10",document.getElementById("searchNotes").checked=!0,document.getElementById("openloginstart").checked=!1,document.getElementById("storeLostOTP").checked=!0,document.getElementById("enablenewlogin").checked=!0,document.getElementById("clearfilledfieldsonlogoff").checked=
!1,document.getElementById("toplevelmatchingsites").checked=!1):0<=b.indexOf("Icons")&&(document.getElementById("icons1").checked=!0)}
function lpReadAllPrefs(b){var c=g_username_hash&&""!=g_username_hash?g_username_hash:"";g_userprefs=[];g_identity="";var d=opendb();createPrefsTable(d);d?d.transaction(function(a){a.executeSql("SELECT * FROM LastPassPreferences where username_hash=? or username_hash=?",[c,""],function(a,c){g_gblprefs=[];for(var d=0;d<c.rows.length;d++){var e=c.rows.item(d).username_hash,j=c.rows.item(d).prefname,k=c.rows.item(d).prefvalue;""!=e?"language"!=j&&(g_userprefs[j]=k,"identity"==j&&(g_identity=k)):g_gblprefs[j]=
k}if(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)d=lpGetPref("language",""),include_language(d);start_idle_checker();"undefined"==typeof g_gblprefs.generateHkKeyCode&&setup_default_hotkeys();setup_hotkeys();if("undefined"!=typeof g_gblprefs.server&&(d=g_gblprefs.server,""!=d&&("lastpass.com"==d||"lastpass.eu"==d)))(0==base_url.indexOf("https://rodan.lastpass.com")||0==base_url.indexOf("https://dev.lastpass.com"))&&"lastpass.com"==d||(base_url="https://"+d+"/");g_prefs_read=!0;console_log("read: "+
c.rows.length+" preferences");b&&b(c.rows.length)},function(a,b){console_log(b)})}):b&&b()}
function setup_default_hotkeys(){g_is_mac?(lpPutGblPref("generateHkKeyCode",0),lpPutGblPref("generateHkMods",""),lpPutGblPref("recheckHkKeyCode",0),lpPutGblPref("recheckHkMods",""),lpPutGblPref("searchHkKeyCode",0),lpPutGblPref("searchHkMods",""),lpPutGblPref("nextHkKeyCode",33),lpPutGblPref("nextHkMods","meta"),lpPutGblPref("prevHkKeyCode",34),lpPutGblPref("prevHkMods","meta"),lpPutGblPref("homeHkKeyCode",0),lpPutGblPref("homeHkMods",""),lpPutGblPref("popoverHkKeyCode",220),lpPutGblPref("popoverHkMods",
"meta")):(lpPutGblPref("generateHkKeyCode",71),lpPutGblPref("generateHkMods","alt"),lpPutGblPref("recheckHkKeyCode",73),lpPutGblPref("recheckHkMods","alt"),lpPutGblPref("searchHkKeyCode",87),lpPutGblPref("searchHkMods","alt"),lpPutGblPref("nextHkKeyCode",33),lpPutGblPref("nextHkMods","alt"),lpPutGblPref("prevHkKeyCode",34),lpPutGblPref("prevHkMods","alt"),lpPutGblPref("homeHkKeyCode",72),lpPutGblPref("homeHkMods","control alt"),lpPutGblPref("popoverHkKeyCode",220),lpPutGblPref("popoverHkMods","alt"));
lpPutGblPref("submitHkKeyCode",0);lpPutGblPref("submitHkMods","");lpPutGblPref("saveallHkKeyCode",0);lpPutGblPref("saveallHkMods","");lpPutGblPref("logoffHkKeyCode",0);lpPutGblPref("logoffHkMods","");lpPutGblPref("defaultffidHkKeyCode",0);lpPutGblPref("defaultffidHkMods","");lpWriteAllPrefs()}
function lpWriteAllPrefs(){var b=g_isfirefoxsdk,c=opendb();createPrefsTable(c);c&&c.transaction(function(c){var a="",f="",h=[],g=0;b&&(a="REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES ");if(null!=g_username_hash&&""!=g_username_hash)for(var e in g_userprefs_changed)b?(a+=f+"(?, ?, ?)",f=", ",h.push(g_username_hash),h.push(e),h.push(g_userprefs[e]),g++):c.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",[g_username_hash,
e,g_userprefs[e]],function(){},function(a,b){console_log(b)});g_userprefs_changed=[];for(e in g_gblprefs_changed)b?(a+=f+"(?, ?, ?)",f=", ",h.push(""),h.push(e),h.push(g_gblprefs[e]),g++):c.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",["",e,g_gblprefs[e]],function(){},function(a,b){console_log(b)});g_gblprefs_changed=[];b&&0<g&&c.executeSql(a,h,function(){},function(b,a){console_log(a)})})}optionsData=[];optionsData.HotKeys=[];
function capturehk(b,c){var d;d=""+(c.ctrlKey?"control":"");d+=c.metaKey?(""!=d?" ":"")+"meta":"";d+=c.altKey?(""!=d?" ":"")+"alt":"";d+=c.shiftKey?(""!=d?" ":"")+"shift":"";if(""==d||"shift"==d)d=getBG().g_is_mac?"meta":"alt";if(8==c.keyCode||127==c.keyCode||46==c.keyCode)optionsData.HotKeys[b+"KeyCode"]=0;else{if(32>=c.keyCode||91==c.keyCode)return;optionsData.HotKeys[b+"KeyCode"]=0!=c.keyCode?c.keyCode:c.charCode}optionsData.HotKeys[b+"Mods"]=d;writeHotKeyValue(b)}
function writeHotKeyValue(b){var c=optionsData.HotKeys[b+"KeyCode"],d=document.getElementById(b),a="";if(0!=c){b=optionsData.HotKeys[b+"Mods"];"string"!=typeof b&&(b="");b=b.split(" ");for(var f in b)"control"==b[f]&&(a+=gs("Ctrl")+"+"),"meta"==b[f]&&(a+=gs("Meta")+"+"),"alt"==b[f]&&(a+=gs("Alt")+"+"),"shift"==b[f]&&(a+=gs("Shift")+"+")}if(0!=c){c=parseInt(c);switch(c){case 33:a+=gs("Page Up");break;case 34:a+=gs("Page Down");break;case 35:a+=gs("End");break;case 36:a+=gs("Home");break;case 37:a+=
gs("Left");break;case 38:a+=gs("Up");break;case 39:a+=gs("Right");break;case 40:a+=gs("Down");break;case 189:a+="-";break;case 219:a+="[";break;case 220:a+="\\";break;case 221:a+="]";break;case 186:a+=";";break;case 222:a+="'";break;case 188:a+=",";break;case 187:a+="+";break;case 190:a+=".";break;case 191:a+="/";break;case 106:a+="*";break;case 192:a+="~";break;case 124:a+=gs("Print Screen");break;default:a+=String.fromCharCode(c).toUpperCase()}d.value=a}else d.value=""}
function fixhk(b,c){32>optionsData.HotKeys[b+"KeyCode"]&&(optionsData.HotKeys[b+"Mods"]="",writeHotKeyValue(b));c.cancelBubble=!0;c.stopPropagation()}var last_idle_check=0,idle_checker_started=!1;
function start_idle_checker(){if(0==last_idle_check&&!idle_checker_started){var b=parseInt(lpGetPref("idleLogoffVal",0));lpdbg("idle","starting idle checker, idleLogoffVal is "+lpGetPref("idleLogoffVal",0));0<b&&(last_idle_check=lp_get_gmt_timestamp(),idle_checker_started=!0,setTimeout(function(){idle_checker()},1E4))}}var last_active_time=0,enable_native_idle=!0;
function idle_checker(){var b=parseInt(lpGetPref("idleLogoffVal",0));lpdbg("idle","checking idle, idleLogoffVal is "+lpGetPref("idleLogoffVal",0));if(0<b){var c=60*b,d=function(a){var d=!1,g=lp_get_gmt_timestamp();"active"==a?last_active_time=lp_get_gmt_timestamp():"locked"==a?d=c<g-last_active_time:"idle"==a&&(d=!0);var e=!0;if(0!=last_idle_check&&0!=c&&(d||c<g-last_idle_check))console_log("IDLE CHECKER ISSUING LOGOFF: idleLogoffVal="+b+" isidle="+d+" limit="+c+" currtime="+g+" last_idle_check="+
last_idle_check+" state="+a+" last_active_time="+last_active_time),lplogoff_if(),e=!1;e&&(last_idle_check=g)},a=function(a){a?call_binary_function("get_idle_ms",function(a){a=parseInt(a/1E3);d(c<a?"idle":"active")}):enable_native_idle&&("undefined"!=typeof chrome&&"undefined"!=typeof chrome.idle)&&chrome.idle.queryState(c,d)};have_binary_function("get_idle_ms")?can_check_idle(a):a(!1)}setTimeout(function(){idle_checker()},1E4)}var g_can_check_idle=-1;
function can_check_idle(b){-1!=g_can_check_idle?b(g_can_check_idle?!0:!1):!g_is_linux||!have_binary_function("can_check_idle")?(g_can_check_idle=1,b(!0)):call_binary_function("can_check_idle",function(c){g_can_check_idle=c?1:0;b(g_can_check_idle?!0:!1)})};
