var data=null,existing=null,origusername=null,origpassword=null,attachnum=0,attaches=[],removedattach=[],g_eye_show=!0,g_eyeimgid=null,g_start_time=null,POLL_MAXTIME=3E5,g_pwlen=0,pass=!0,g_pw_field_ids=[],ENABLE_ONLY=!0,g_do_keyaccel=!0,KEY_S=83,event_handlers={};
function fix_event_handlers(){lpdbg("site","fixing event handlers");for(var a in event_handlers){lpdbg("site","setting event handler for "+a);var c=document.getElementById("fields").contentWindow.document.getElementById(a);c?(c.onclick=event_handlers[a],lpdbg("site","set event handler for "+a)):lpdbg("site","could not find "+a)}}
function onLoad(a){clearData();if(a){var c=getBG(),d;c.g_site_data&&(d=c.g_site_data.aid);if("undefined"==typeof d)data=c.g_site_data;else{data=c.g_site_data;var b=!1;"undefined"!==typeof c.g_site_data.save_all&&!0==c.g_site_data.save_all&&(b=!0);a=get_record(d);for(var k in a)data[k]=a[k]}c.g_generatedpw&&(document.getElementById("pwprotect").style.visibility="hidden",document.getElementById("pwprotectlabel").style.visibility="hidden");if((existing=data&&"undefined"!=typeof get_record_id(data)&&
get_record_id(data)&&""!=get_record_id(data)&&"0"!=get_record_id(data))&&!c.LPISLOC&&c.g_showhistorylinks)document.getElementById("usernamehistory").style.display="inline",document.getElementById("passwordhistory").style.display="inline";if(data){a=issharedfolder(c.g_shares,data.group);var h=!1==a?c.g_local_key:a.sharekey;"http://sn"==data.url&&c.loglogin(get_record_id(data));a=!1;if(is_application(data)){document.getElementById("usernamehistory").style.display="none";document.getElementById("passwordhistory").style.display=
"none";document.getElementById("urltext").innerHTML=gs("Application:");document.getElementById("url").value=data.appname;var e=0,f=0,j;for(j in data.fields)if(data.fields.hasOwnProperty(j))if(""==data.fields[j].type){if(1<++e)break}else if("password"==data.fields[j].type&&1<++f)break;if(1!=e||1!=f)a=!0}else if(e=AES._utf8_decode(data.url),existing||!(0<=e.indexOf("homelocal")))document.getElementById("url").value=e;event_handlers={};data.editfields?(document.title=is_application(data)?gs("Edit Application Fields"):
gs("Edit Site Fields"),document.getElementById("siteactions").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("namegrouprow").style.display="none",document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("notesrow1").style.display="none",document.getElementById("notesrow2").style.display="none",document.getElementById("advsettingswrap").style.display="none",document.getElementById("cpwfieldbtn").style.display="none",
document.getElementById("fieldsrow2").style.display="block",document.getElementById("fields").contentWindow.document.body.appendChild(getFieldsHTMLNodes(h))):data.save_all||a?(document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("fieldsrow1").style.display="block",document.getElementById("fieldsrow2").style.display="block",existing?(document.title=is_application(data)?gs("Edit Application"):gs("Edit Site"),document.getElementById("fields").contentWindow.document.body.appendChild(getFieldsHTMLNodes(h))):
(document.title=gs("Add Site"),document.getElementById("fields").contentWindow.document.body.innerHTML=getDataHTML())):data.sn?(document.title=existing?gs("Edit Secure Note"):gs("Add Secure Note"),document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("addrow").style.display="block",showadvpane()):existing?(is_application(data)?(document.title=gs("Edit Application"),document.getElementById("username").value=
getusernamefromacct(data),document.getElementById("password").value=getpasswordfromacct(data),origusername=c.lpmenc(document.getElementById("username").value,!0,h),origpassword=c.lpmenc(document.getElementById("password").value,!0,h)):(document.title=gs("Edit Site"),document.getElementById("username").value=data.unencryptedUsername,g_pwlen=(a=c.lpmdec(data.password,!0,h))?a.length:-1,g_pwlen=""==data.password?0:g_pwlen,document.getElementById("password").value=a,origusername=data.username,origpassword=
data.password),document.getElementById("editfields").style.display="inline"):(document.title=gs("Add Site"),document.getElementById("username").value=data.username,document.getElementById("password").value=data.password,disable_CPWButton());fix_event_handlers();!existing&&("undefined"!=typeof data.addsite&&-1==AES._utf8_decode(data.url).indexOf("homelocal"))&&(document.getElementById("group").value=get_default_group(data.url),document.getElementById("name").value=c.getname_url(data.url));existing?
(document.getElementById("name").value=data.name,document.getElementById("group").value=data.group,a=c.lpmdec(data.extra,!0,h),document.getElementById("notes").value=a,document.getElementById("fav").checked="1"==data.fav,document.getElementById("pwprotect").checked=data.pwprotect,document.getElementById("autologin").checked=data.autologin&&"0"!=data.autologin,is_application(data)?document.getElementById("never_autofill_td").style.visibility="hidden":document.getElementById("never_autofill").checked=
data.never_autofill):data.sn&&(document.getElementById("group").value=gs("Secure Notes"));1==data.sn&&(document.getElementById("favcheck").style.display="none",document.getElementById("never_autofill_td").style.display="none",document.getElementById("autologingrp").style.visibility="hidden")}existing&&!data.editfields?(document.getElementById("del").style.display="inline-block",a=get_record(get_record_id(data)),document.getElementById("share").style.display=!c.LPISLOC&&!a.genpw&&("undefined"==typeof a.sharedfromaid||
null==a.sharedfromaid||""==a.sharedfromaid||"0"==a.sharedfromaid||"null"==a.sharedfromaid)&&"undefined"==typeof a.sharefolderid&&!is_application(a)?"inline-block":"none"):(document.getElementById("del").style.display="none",document.getElementById("share").style.display="none");a=[];for(d in c.g_sites)c.check_ident_aid(d)&&(e=c.g_sites[d].group,""!=e&&!lp_in_array(e,a)&&(a[a.length]=e));for(d in c.g_securenotes)c.check_ident_aid(d)&&(e=c.g_securenotes[d].group,""!=e&&!lp_in_array(e,a)&&(a[a.length]=
e));for(d in c.g_applications)c.check_ident_appaid(d)&&(e=c.g_applications[d].group,""!=e&&!lp_in_array(e,a)&&(a[a.length]=e));a.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});if(!existing&&data&&!data.save_all&&!data.noreplace){e=c.getsites(lp_gettld_url(data.url),!0);d=[];for(j in e)d[d.length]=j;d.sort(function(a,b){return c.g_sites[a].name.toLowerCase()<c.g_sites[b].name.toLowerCase()?-1:1});e=document.getElementById("replaceexistingsiteaid");for(j=0;j<d.length;j++)f=c.g_sites[d[j]].name,
typeof c.g_sites[d[j]].useusername&&""!=c.g_sites[d[j]].useusername&&(f+=" ("+c.g_sites[d[j]].useusername+")"),e.options[e.options.length]=new Option(f,d[j]);if(1<e.options.length)for(j=1;4>=j;j++)document.getElementById("addreplacerow"+j).style.display="block"}document.getElementById("metercontainer").innerHTML=ghetto_meter(280,!0);stylize_ghetto_meter(document,280);update_password_meter("",document.getElementById("password").value);data&&data.last_pwchange_gmt&&pw_age_update(data.last_pwchange_gmt);
show_cpw_button(data);my_aid=get_record_id(data);buildSecureNotes(existing);onResize();create_combo("group",a,!0,document,"","group",-22,5);setup_eye_events(document);(getBG().g_is_win||getBG().g_is_mac||getBG().g_is_linux)&&setTimeout(function(){decryptThumbnails(h)},0);document.getElementById("advsettings").addEventListener("click",showadvpane);document.getElementById("_docwrite_site14a").addEventListener("click",showadvpane);document.getElementById("fav").addEventListener("change",echoFavorite);
echoFavorite();null!==document.getElementById("name")&&null!==document.getElementById("notestype")&&(document.getElementById("name").addEventListener("keyup",function(){setTimeout(updateFormHeading,100)}),updateFormHeading());data&&data.openchpw&&show_cpw_dialog("new");data=c.g_site_data;for(k in c.g_site_data)data[k]=c.g_site_data[k];b&&(data.save_all=!0);c.g_site_data=null}else get_data("site",function(){onLoad(!0)})}
function updateFormHeading(){""!=document.getElementById("notestype").value?set_innertext(document.getElementById("dynheader"),document.getElementById("name").value+" - "+document.getElementById("notestype").value+(1==data.sn?" "+gs("Secure Note"):"")):(document.getElementById("dynheader").style.display="none",document.getElementById("dynbody").style.backgroundColor="transparent")}
function showadvpane(){var a=document.getElementById("advsettings"),c=document.getElementById("checkboxrow1");a.classList.toggle("turn90");c.classList.toggle("displaynone")}
function echoFavorite(){document.getElementById("fav").checked?(document.getElementById("echo_favorite").src="images/favorite.png",document.getElementById("_docwrite_site15").innerHTML=gs("Remove Favorite"),document.getElementById("_docwrite_site34").innerHTML=gs("Remove Site from Favorites")):(document.getElementById("echo_favorite").src="images/not_favorite.png",document.getElementById("_docwrite_site15").innerHTML=gs("Make Favorite"),document.getElementById("_docwrite_site34").innerHTML=gs("Add Site to Favorites"))}
function decryptThumbnails(a){if("undefined"!=typeof data&&(null!==data&&1==data.sn)&&(document.getElementById("lpaddattach").style.display="block","undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)){getBG();num_attachments=data.attaches.length;for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&(addThumbnail(data.attaches[c].id,data.attaches[c].mimetype,data.attaches[c].bytes,data.attaches[c].filename,data.attachkey,a),num_attachments--)}}
function buildSecureNotes(a){if("undefined"!=typeof data&&null!==data&&"undefined"!=typeof data.sn&&1==data.sn){document.getElementById("notesrow0").style.display="block";document.getElementById("notesrow1").style.display="none";document.getElementById("notehistory").style.display="inline-block";document.getElementById("group").style.width="auto";document.getElementById("group").spellcheck=!1;var c=document.getElementById("notestype").val,d=[],b;for(b in sntemplates){var k="undefined"!=typeof sntemplateicons[b]?
sntemplateicons[b]:geticonurl("sn");d[d.length]={label:gs(b),image:k,value:b}}a||(create_combo("notestype",d,!0,document,"","notestype",-22,5),document.getElementById("notestype").addEventListener("click",function(){openCombo(null,"notestype","notestype_combo",document)}));a&&(c=getNoteValue("NoteType",document.getElementById("notes").value));if(!c||"undefined"==typeof sntemplates[c])c="Generic";init_attachment_action_menu();document.getElementById("autologingrp").setAttribute("colspan","0");a=document.getElementById("pwaginggrp");
null!=a&&a.setAttribute("colspan","2");buildForm(c);onResize()}else document.getElementById("attachtabletr").style.width="0px"}function disable_CPWButton(){document.getElementById("cpwbtnmini").classList.add("btn_disabled");document.getElementById("cpwfieldbtn")&&document.getElementById("cpwfieldbtn").classList.add("btn_disabled")}function disable_SaveButton(){document.getElementById("save").classList.add("btn_disabled")}
function enable_SaveButton(){document.getElementById("save").classList.remove("btn_disabled")}function update_SaveButton(a){var c=document,d=c.getElementById("save");c&&d&&(check_for_changes()?0<=d.className.indexOf("btn_disabled")&&enable_SaveButton():a!=ENABLE_ONLY&&-1==d.className.indexOf("btn_disabled")&&disable_SaveButton())}
function buildForm(a){var c=document.getElementById("notestype");c.value=gs(a);c.val=a;var d="undefined"!=typeof sntemplateicons[a]?sntemplateicons[a]:geticonurl("sn");c.style.background="url("+d+") no-repeat 2px 2px"+(existing?" rgb(238,238,238)":" rgb(249,249,249)");document.getElementById("notesrow2").style.display="Generic"==a?"block":"none";document.getElementById("notesrow3").style.display="Generic"==a?"none":"block";document.getElementById("notestype").disabled=existing?!0:!1;if("Generic"!=
a){for(c=document.getElementById("dynamicnotes");c.hasChildNodes()&&0<c.childNodes.length;)c.removeChild(c.firstChild);d=sntemplates[a];a=document.createElement("table");a.style.width="100%";a.style.borderSpacing="0px";for(var b in d){var k=document.createElement("tr"),h=document.createElement("td");h.style.whiteSpace="nowrap";var e=document.createElement("td");e.style.width="100%";var f=document.createTextNode(gsproper(b)+":");h.appendChild(f);var j=f=null;if("text"==d[b])f=document.createElement("input"),
f.type="text",f.spellcheck=!1,f.id="note_"+b,f.style.width="100%",f.style.fontFamily="Courier",existing&&(f.value=getNoteValue(b,document.getElementById("notes").value),"Private Key"==b&&(j=document.createElement("a"),j.innerHTML=" Copy Key",j.style.textDecoration="none",j.style.cursor="pointer",j.style.height="15px",j.style.align="right",j.onclick=-1==f.value.indexOf("-----BEGIN")&&-1==f.value.indexOf("END-----")?function(){var a=document.getElementById("note_Private Key").value;getBG().copytoclipboard(a)}:
function(){var a=document.getElementById("note_Private Key");pkelparse=a.value.split(/-----BEGIN.*KEY----- | -----END.*KEY-----/);pkelarmor=a.value.split(/-----/);var a="",b;for(b in pkelparse[1])a=":"!=pkelparse[1].charAt(b-1)?a+pkelparse[1][b].replace(/\u0020/g,"\n"):a+pkelparse[1][b];pktotal="-----"+pkelarmor[1]+"-----\n"+a+"\n-----"+pkelarmor[3]+"-----";getBG().copytoclipboard(pktotal);return!1})),"Password"==b&&(f.type="password",j=document.createElement("img"),j.id="note_eye_img",j.src="images/eye-shown.png",
j.style.textDecoration="none",j.style.position="relative",j.style.top="6px",j.style.left="-22px",j.onclick=function(){var a=document.getElementById("note_Password");-1!==document.getElementById("note_eye_img").src.indexOf("images/eye-shown.png")?document.getElementById("note_eye_img").src="images/eye-hidden.png":document.getElementById("note_eye_img").src="images/eye-shown.png";a.type="password"==a.type?"text":"password"});else if("date"==d[b]||"datemoyr"==d[b]){f=document.createElement("span");f.style.width=
"100%";var g=document.createElement("select");g.id="note_"+b+"_mo";g.style.width="auto";var n="January February March April May June July August September October November December".split(" "),l;for(l in n)g.options[g.options.length]=new Option(gs(n[l]),n[l]);var r=null;if(existing&&((r=getNoteValue(b,document.getElementById("notes").value))&&(r=r.split(",")),r&&0<r.length))for(var p in n)if(n[p]==r[0]||gs(n[p])==r[0]){g.value=n[p];break}f.appendChild(g);if("date"==d[b]){g=document.createElement("select");
g.id="note_"+b+"_day";for(l=1;31>=l;l++)g.options[g.options.length]=new Option(l,l);r&&1<r.length&&(g.value=r[1]);f.appendChild(g)}g=document.createElement("input");g.type="text";g.maxLength=4;g.size=4;g.spellcheck=!1;g.id="note_"+b+"_yr";n="date"==d[b]?2:1;r&&r.length>n&&(g.value=r[n]);f.appendChild(g)}else if("textarea"==d[b])h.style.verticalAlign="top",f=document.createElement("textarea"),f.cols=30,f.spellcheck=!1,f.rows=7,f.id="note_"+b,f.style.width="100%",existing&&(f.value=getNoteValue(b,document.getElementById("notes").value,
!0));else continue;e.appendChild(f);null!==j&&e.appendChild(j);k.appendChild(h);k.appendChild(e);a.appendChild(k)}b=document.createElement("fieldset");b.appendChild(a);c.appendChild(b);updateFormHeading()}}function onResize(){}
function fix_addreplace(){document.getElementById("addnewsite").checked?(document.getElementById("url").disabled=!1,document.getElementById("name").disabled=!1,document.getElementById("group").disabled=!1,document.getElementById("username").disabled=!1,document.getElementById("password").disabled=!1,document.getElementById("notes").disabled=!1,document.getElementById("fav").disabled=!1,document.getElementById("never_autofill").disabled=!1,document.getElementById("pwprotect").disabled=!1,document.getElementById("autologin").disabled=
!1,document.getElementById("replaceexistingsiteaid").disabled=!0):document.getElementById("replaceexistingsite").checked&&(document.getElementById("url").disabled=!0,document.getElementById("name").disabled=!0,document.getElementById("group").disabled=!0,document.getElementById("username").disabled=!0,document.getElementById("password").disabled=!0,document.getElementById("notes").disabled=!0,document.getElementById("fav").disabled=!0,document.getElementById("never_autofill").disabled=!0,document.getElementById("pwprotect").disabled=
!0,document.getElementById("autologin").disabled=!0,document.getElementById("replaceexistingsiteaid").disabled=!1)}
function getSecureNoteFromFields(){if("undefined"!=typeof data&&1==data.sn){var a=document.getElementById("notestype").val;if("Generic"==a||"none"==document.getElementById("notesrow0").style.display)return document.getElementById("notes").value;var c="NoteType:"+a+"\n",d;for(d in sntemplates[a])"text"==sntemplates[a][d]?c+=d+":"+document.getElementById("note_"+d).value+"\n":"date"==sntemplates[a][d]||"datemoyr"==sntemplates[a][d]?(c+=d+":"+document.getElementById("note_"+d+"_mo").value,"date"==sntemplates[a][d]&&
(c+=","+document.getElementById("note_"+d+"_day").value),c+=","+document.getElementById("note_"+d+"_yr").value+"\n"):"textarea"==sntemplates[a][d]&&(c+=d+":"+document.getElementById("note_"+d).value+"\n");return c}return document.getElementById("notes").value}function get_decrypted_attachdata(a){for(var c in g_encatt)if("undefined"!=typeof g_encatt[c].id&&g_encatt[c].id==a)return g_encatt[c].data;return""}
function dosave(a,c){var d=document.getElementById("replaceexistingsite").checked;if(d&&0==document.getElementById("replaceexistingsiteaid").selectedIndex)alert(gs("Please Make a Selection"));else{var b=getBG();if(b.lploggedin)if(data.editfields){var k=issharedfolder(b.g_shares,data.group);if(checkreadonly(k)){var h=!1==k?b.g_local_key:k.sharekey;if(is_application(data)){var e=get_record(get_record_id(data));e.last_touch=lp_get_gmt_timestamp();for(var f in e.fields){var d=e.fields[f],j=document.getElementById("fields").contentWindow.document.getElementById(d.htmlid);
j&&(d.value=b.lpmenc(j.value,!0,h))}var g="appaid="+b.en(e.appaid);for(f in e.fields)d=e.fields[f],g+="&fieldid"+f+"="+b.en(d.id)+"&fieldtype"+f+"="+b.en(d.type)+"&fieldvalue"+f+"="+b.en(crypto_btoa(d.value));g+=!1==k?"":"&sharedfolderid="+b.en(k.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(g,e)}else checkFieldsForUpdates(h);getBG().close_editfieldsopener();setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}}else{var e=punycode.URLToASCII(trim(document.getElementById("url").value)),n=document.getElementById("name").value,g=document.getElementById("group").value,l=document.getElementById("username").value,r=document.getElementById("password").value,p=getSecureNoteFromFields(),s=document.getElementById("fav").checked,j=document.getElementById("never_autofill").checked,w=document.getElementById("pwprotect").checked,q=document.getElementById("autologin").checked;if(0<g_pwlen&&0==r.length||-1==g_pwlen&&
0==r.length)if(h=gs("Are you sure you want to save an empty password?"),!confirm(h))return;k=issharedfolder(b.g_shares,g);if(checkreadonly(k)){var x=!1;if(existing&&g!=data.group){if(x=issharedfolder(b.g_shares,data.group),!checkmove(k,x))return}else existing&&(x=k);h=existing?!1==x?b.g_local_key:x.sharekey:!1==k?b.g_local_key:k.sharekey;d&&(q=b.g_sites[document.getElementById("replaceexistingsiteaid").value],n=q.name,g=q.group,k=issharedfolder(b.g_shares,g),h=!1==k?b.g_local_key:k.sharekey,p=b.lpmdec(q.extra,
!0,h),s="1"==q.fav,j=q.never_autofill,w=q.pwprotect,q=q.autologin);if(""==n)alert(gs("You must enter a name."));else{if(45E3<p.length)if(confirm(gs("The notes field contains too much data.  You may store a maximum of 45,000 characters per note.\n\nWould you like us to truncate the note for you?  You will lose some of your data.")))p=p.substring(0,45E3);else return;var u=!1;if(existing&&g!=data.group&&(k||x)){var m=[get_record_id(data)],t=[];t[get_record_id(data)]=g;u=!0;if(!b.moveIntoSharedFolder(k,
x,m,t,!1,!0))return}if(existing&&is_application(data)){e=get_record(get_record_id(data));e.last_touch=lp_get_gmt_timestamp();n=getusernamefromacct(e);s=getpasswordfromacct(e);for(f in e.fields)if(d=e.fields[f],j=document.getElementById("fieldsrow2"),"none"!=window.getComputedStyle(j).display){if(j=document.getElementById("fields").contentWindow.document.getElementById(d.htmlid))d.value=b.lpmenc(j.value,!0,h)}else""==d.type&&b.lpmdec_acct(d.value,!0,e,b.g_shares)==n?d.value=b.lpmenc(document.getElementById("username").value,
!0,h):"password"==d.type&&b.lpmdec_acct(d.value,!0,e,b.g_shares)==s&&(d.value=b.lpmenc(document.getElementById("password").value,!0,h));e.name=document.getElementById("name").value;e.group=document.getElementById("group").value;e.appname=document.getElementById("url").value;d=getSecureNoteFromFields();d!=b.lpmdec(e.extra,!0,h)&&(e.extra=lpmenc(d,!0,h));e.fav=document.getElementById("fav").checked?"1":"0";e.pwprotect=document.getElementById("pwprotect").checked;e.autologin=document.getElementById("autologin").checked?
"1":"0";var v=e.group;k&&(e.sharefolderid=k.id,v=v.substr(k.decsharename.length+1));if(g!=data.group&&(k||x))m=[get_record_id(data)],t=[],t[get_record_id(data)]=g,b.moveIntoSharedFolder(k,x,m,t,!1,!1,!0);else{g="ajax=1&extjs=1&cmd=updatelpaa&name="+b.en(b.lpenc(e.name,h))+"&grouping="+b.en(b.lpenc(v,h))+"&appname="+b.en(e.appname)+"&extra="+b.en(crypto_btoa(e.extra))+"&appaid="+b.en(e.appaid);"1"==e.fav&&(g+="&fav=on");e.pwprotect&&(g+="&pwprotect=on");"1"==e.autologin&&(g+="&autologin=on");for(f in e.fields)d=
e.fields[f],g+="&fieldid"+f+"="+b.en(d.id)+"&fieldtype"+f+"="+b.en(d.type)+"&fieldvalue"+f+"="+b.en(crypto_btoa(d.value));g+=!1==k?"":"&sharedfolderid="+b.en(k.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(g,e)}setTimeout(function(){getBG().closecurrenttab("site.html")},0)}else{m=existing?data.sn?b.g_securenotes[get_record_id(data)]:b.g_sites[get_record_id(data)]:b.createNewAcct();v=!1;
for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(v=!0);if(v&&!c){"undefined"==typeof m.attachkey||""==m.attachkey?(t=SHA256(lpCreatePass(32,1,1,1,1,1,1,1)),g_attachkey=b.lpenc(t,h)):g_attachkey=m.attachkey;var t=AES.hex2bin(b.lpdec(g_attachkey,h)),y=[];for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(attaches[f].filename=lpenc(attaches[f].filename,t),y[y.length]={id:attaches[f].id,bytes:attaches[f].bytes});if(y.length){b.fastEncryptAttachments(t,
y,function(a){g_encatt=a;dosave(null,!0)});return}}y=lp_gettld_url(AES._utf8_encode(e));if(existing&&!data.sn&&m.tld!=y&&!a&&b.g_prompts.view_pw_prompt)b.security_prompt(function(){dosave(1,c)});else{existing&&!m.sn&&b.fix_tlds(m.tld,y,get_record_id(data));m.genpw=!1;m.name=n;u||(m.group=g);"http://sn"==e?(m.url=e,m.sn=1):m.url=AES._utf8_encode(e);m.tld=y;m.unencryptedUsername=l;l!=b.lpmdec(m.username,!0,h)&&(m.username=b.lpmenc(l,!0,h));r!=b.lpmdec(m.password,!0,h)&&(m.password=b.lpmenc(r,!0,h));
p!=b.lpmdec(m.extra,!0,h)&&(m.extra=b.lpmenc(p,!0,h));m.fav=s?"1":"0";m.autologin=q;m.never_autofill=j;m.pwprotect=w;existing||(m.aid="0");!1!=k&&(m.sharefolderid=k.id,0==k.give&&(m.sharedfromaid=1));u="";t=[];if(v){if("undefined"==typeof m.attachkey||""==m.attachkey)m.attachkey=g_attachkey,u+="&attachkey="+b.en(m.attachkey);m.attachpresent="1";m.retrieveattach=1;v=0;for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(u+="&filename"+v+"="+b.en(attaches[f].filename),u+=
"&mimetype"+v+"="+b.en(attaches[f].mimetype),u+="&attachid"+v+"="+b.en(attaches[f].id),u+="&attachbytes"+v+"="+b.en(get_decrypted_attachdata(attaches[f].id)),"undefined"==typeof t.add&&(t.add=[]),t.add[t.add.length]=existing?{id:m.aid+"-"+attaches[f].id,mimetype:attaches[f].mimetype,parent:m.aid,filename:attaches[f].filename}:{id:attaches[f].id,mimetype:attaches[f].mimetype,filename:attaches[f].filename},v++)}if(0<removedattach.length){m.retrieveattach=1;for(f=0;f<removedattach.length;f++)u+="&rmattach"+
f+"="+b.en(removedattach[f]),"undefined"==typeof t.remove&&(t.remove=[]),t.remove[t.remove.length]=removedattach[f]}v=g;k&&(v=g.substr(k.decsharename.length+1));if(existing){if(e!=data.url||n!=data.name||g!=data.group||l!=data.unencryptedUsername||r!=b.lpmdec(data.password,!0,h)||p!=b.lpmdec(data.extra,!0,h)||s!=("1"==data.fav)||j!=data.never_autofill||w!=data.pwprotect||q!=data.autologin||0<attaches.length||0<removedattach.length){m.sn?b.g_securenotes[m.aid]=m:b.g_sites[m.aid]=m;for(f in m.fields)if(m.fields.hasOwnProperty(f)&&
(d=m.fields[f],is_encrypted_field(d.type)&&(null!=origpassword&&""!=origpassword&&null!=d.value&&""!=d.value&&b.lpmdec_acct(d.value,!0,m,b.g_shares)==b.lpmdec_acct(origpassword,!0,m,b.g_shares))&&"password"==d.type&&(d.value=m.password),is_encrypted_field(d.type)&&(null!=origusername&&""!=origusername&&null!=d.value&&""!=d.value&&b.lpmdec_acct(d.value,!0,m,b.g_shares)==b.lpmdec_acct(origusername,!0,m,b.g_shares))&&("text"==d.type||"email"==d.type||"tel"==d.type||"url"==d.type)))d.value=m.username;
if(g!=data.group&&(k||x)){m=[get_record_id(data)];t=[];t[get_record_id(data)]=g;b.moveIntoSharedFolder(k,x,m,t,!1,!1,!0);setTimeout(function(){getBG().closecurrenttab("site.html")},0);return}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.applyattacharraychanges(t);b.increment_local_accts_version();b.rewritelocalfile();g="ajax=1&extjs=1&name="+b.en(b.lpenc(n,h))+"&url="+b.en(AES.url2hex(e))+"&grouping="+b.en(b.lpenc(v,h))+"&username="+b.en(crypto_btoa(m.username))+
"&password="+b.en(crypto_btoa(m.password))+"&extra="+b.en(crypto_btoa(m.extra))+"&openid_url=&aid="+b.en(get_record_id(data))+"&basic_auth=0&isbookmark=0&localupdate=1";g=g+(w?"&pwprotect=on":"")+(j?"&never_autofill=on":"");g+=q?"&autologin=on":"";g+=s?"&fav=on":"";g+=!1==k?"":"&sharedfolderid="+b.en(k.id);"http://sn"==e&&("undefined"!==typeof b.g_loglogins&&b.g_loglogins)&&(g+="&n="+AES.url2hex(n));g+=u;m.attacharraychanges=t;m.newvalues=[];b.saveSite(g,m);k=b.getsites(y,!0);r!=b.lpmdec(data.password,
!0,h)&&1<array_length(k)&&b.openLinkedSites(r,y,get_record_id(data))}data.save_all&&checkFieldsForUpdates(h)}else m.fields=[],f=[],g=updateAndEncryptData2(b,m.username,m.password,m.fields,m,f,h),g="name="+b.en(b.lpenc(n,h))+"&grouping="+b.en(b.lpenc(v,h))+"&data="+b.en(b.bin2hex(g))+"&extra="+b.en(b.lpenc(p,h))+(w?"&pwprotect=on":"")+(j?"&never_autofill=on":"")+(q?"&autologin=on":"")+(s?"&fav=on":""),g+="&extjs=1&localupdate=1",g+=!1==k?"":"&sharedfolderid="+b.en(k.id),"undefined"!=typeof data.realm&&
(m.realm=b.lpmenc(data.realm,!0,h),m.basic_auth="1",g+="&basic_auth=1&realm="+b.en(b.lpenc(m.realm,h))),"http://sn"==e&&(h=getNoteValue("NoteType",p),m.notetype=h,g+=h&&""!=h?"&notetype="+b.en(h):""),d&&(g+="&replacing=1"),g+=u,data.save_all?(m.save_all=!0,g+="&ajax=1&aid=0&save_all=1&url="+b.en(AES.url2hex(e))+"&openid_url=&username=&password=",m.newvalues=f,b.saveAllSite(g,m)):"undefined"!=typeof data.formdata?(g+="&ref="+b.en(AES.url2hex(e)),d&&(g+="&aid="+b.en(document.getElementById("replaceexistingsiteaid").value)),
"undefined"!=typeof data.createacct&&(data.createacct&&"undefined"!=typeof data.username_field)&&(m.fields=[],g+="&createacct=1&username_field="+b.en(data.username_field)),m.newvalues=f,b.saveSiteFromSubmit(g,m)):(g+="&ajax=1&aid=0&url="+b.en(AES.url2hex(e))+"&openid_url=&username="+b.en(crypto_btoa(m.username))+"&password="+b.en(crypto_btoa(m.password)),m.newvalues=f,m.attacharraychanges=t,b.saveSite(g,m));setTimeout(function(){getBG().closecurrenttab("site.html")},0)}}}}}else console_log("Not logged in!")}}
function checkFieldsForUpdates(a){var c=getBG(),d=document.getElementById("fields").contentWindow.document,b=!1,k;for(k in data.fields){var h=data.fields[k];if(is_encrypted_field(h.type)){var e=d.getElementById(h.htmlid);if(e&&"undefined"!=typeof e.value&&c.lpmdec(h.value,!0,a)!=e.value){var b=!0,f=c.lpmenc(e.value,!0,a);""!=h.value&&(""!=c.g_sites[get_record_id(data)].username&&h.value==c.g_sites[get_record_id(data)].username&&""!=e.value)&&(c.g_sites[get_record_id(data)].username=f,c.g_sites[get_record_id(data)].unencryptedUsername=
e.value);""!=h.value&&(""!=c.g_sites[get_record_id(data)].password&&h.value==c.g_sites[get_record_id(data)].password&&""!=e.value)&&(c.g_sites[get_record_id(data)].password=f);h.value=f}}else if("checkbox"==h.type||"radio"==h.type)e=h.checked,f=d.getElementById(h.htmlid)&&d.getElementById(h.htmlid).checked,e!=f&&(b=!0,h.checked=f);else if("select-one"==h.type&&h.faketype&&(e=d.getElementById(h.htmlid))&&"undefined"!=typeof e.value&&h.value!=e.value)b=!0,h.value=e.value}if(b){if(g_issafari||g_isopera||
g_ismaxthon||g_isfirefoxsdk)c.update_site(get_record_id(data)),c.update_fields(get_record_id(data),data.fields);c.increment_local_accts_version();c.rewritelocalfile();a="update=1&aid="+c.en(get_record_id(data))+"&urid=0";b="";e=[];for(k in data.fields)if(h=data.fields[k],h.htmlid&&d.getElementById(h.htmlid))if(f=data.editfields&&""==h.formname?"_"+h.name:"_"+h.formname+"_"+h.name,is_encrypted_field(h.type)){var j=d.getElementById(h.htmlid).value;e.push(j);j=crypto_btoa(h.value);b+=f+"="+c.en(j)+"&"}else"checkbox"==
h.type?d.getElementById(h.htmlid).checked&&(b+=f+"="+c.en(h.value)+"&"):"select-one"==h.type&&h.faketype&&(j=d.getElementById(h.htmlid).value,b+=f+"="+c.en(j)+"&");b+="&auto=1";d=issharedfolder(c.g_shares,data.group);b+=!1==d?"":"&sharedfolderid="+c.en(d.id);c.saveFields(a,b,{url:base_url+"fields.php?"+a,aid:data.aid,postdata:b,param:null,newvalues:e})}}
function updateAndEncryptData2(a,c,d,b,k,h,e){for(var f="",j="undefined"!=typeof data.formdata?data.formdata.split("\n"):[],g=!1,n=0,l=0,r=0;r<j.length;r++){var p=j[r],p=p.split("\t");4!=p.length&&5!=p.length||("text"==p[3]||"email"==p[3]||"tel"==p[3]||"url"==p[3]?n++:"password"==p[3]&&l++)}0==n&&(2==l&&!data.save_all)&&(g=!0);for(r=0;r<j.length;r++)if(p=j[r],p=p.split("\t"),!(4!=p.length&&5!=p.length)){var n=data.save_all?decodeURIComponent(p[0]):"0",l=decodeURIComponent(p[1]),s=decodeURIComponent(p[2]),
w=getBG().lpmenc(s,!0,e),p=p[3];if("text"==p||"password"==p||"hidden"==p||"textarea"==p||"email"==p||"tel"==p||"url"==p){if("email"==p&&s==data.username&&(w=c),"tel"==p&&s==data.username&&(w=c),"url"==p&&s==data.username&&(w=c),"text"==p&&s==data.username&&(w=c),"password"==p&&g?(w=c,g=!1):"password"==p&&s==data.password&&(w=d),s=lpmdec(w,!0,e),h&&h.push(s),f+=n+"\t"+a.en(l)+"\t"+a.en(crypto_btoa(w))+"\t"+a.en(p)+"\n","hidden"!=p){var q=[];q.otherfield=data.save_all;q.name=l;q.type=p;q.value=w;q.checked=
!1;q.formname=data.save_all?n:"";q.urid="0";q.otherlogin="0";q.url="";b[b.length]=q}}else if("action"==p)f+=n+"\taction\t"+a.en(s)+"\taction\n",k.action=AES.url2hex(s);else if("method"==p)f+=n+"\tmethod\t"+a.en(s)+"\tmethod\n",k.method=s;else if(f+=n+"\t"+a.en(l)+"\t"+a.en(s)+"\t"+a.en(p)+"\n","checkbox"==p||"radio"==p||"select-one"==p)q=[],q.otherfield=data.save_all,q.name=l,q.type=p,"checkbox"==p||"radio"==p?(q.checked="-1"==s.substring(s.length-2),q.value=s.substring(0,s.length-2)):q.value=s,q.formname=
data.save_all?n:"",q.urid="0",q.otherlogin="0",q.url="",b[b.length]=q}return f}
function getDataHTML(){for(var a='<link rel="stylesheet" type="text/css" href="general.css">',c=data.formdata.split("\n"),d=0;d<c.length;d++){var b=c[d].split("\t");if(!(4!=b.length&&5!=b.length)){var k=data.save_all?decodeURIComponent(b[0]):"0",h=decodeURIComponent(b[1]),e=decodeURIComponent(b[2]),b=b[3],k=uniqid(k+"_"+h);if("text"==b||"password"==b||"email"==b||"tel"==b||"url"==b)a+=ofja(h)+' <input readonly id="'+ofja(k)+'" name="'+ofja(h)+'" type="'+ofja(b)+'" value="'+ofa(e)+'">',"password"==
b&&(event_handlers[k+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1},g_eyeimgid=k+"toggleimg",a+=' <a id="'+ofja(k)+'toggle" href="#" class="eye"><img id = "'+ofja(g_eyeimgid)+'" src="images/eye-shown.png" alt="'+gs("[Show]")+'"/></a>'),a+="<br>";else if("textarea"==b)a+=ofja(h)+' <textarea readonly name="'+ofja(h)+'">'+ofa(e)+"</textarea><br>";else if("select-one"==b)a+=ofja(h)+
' <select name="'+ofja(h)+'"><option value="'+ofa(e)+'">'+ofa(e)+"</option></select><br>";else if("checkbox"==b||"radio"==b)checked="-1"==e.substring(e.length-2)?" checked":"","radio"==b&&""==checked||(e=e.substring(0,e.length-2),a+='<input disabled type="'+ofja(b)+'" value="'+ofa(e)+'"'+checked+"> "+ofja(h)+"<br>")}}return a}
function showaddfield(){var a=getBG(),a=issharedfolder(a.g_shares,data.group);checkreadonly(a)&&(a=document.getElementById("fields").contentWindow.document,a.getElementById("addfield").style.display="block",a.getElementById("newname").focus())}
function doaddfield(){var a=getBG(),c=issharedfolder(a.g_shares,data.group);if(checkreadonly(c)){var d=document.getElementById("fields").contentWindow.document,b=d.getElementById("newname").value,k=d.getElementById("newtype").value,h=k;"select-one"==h&&(h="text");var e=d.getElementById("newformname")?d.getElementById("newformname").value:"";if(""==b)alert(gs("You must enter a name."));else{for(var f in data.fields)if(data.fields[f].name==b&&(data.editfields||data.fields[f].formname==e)){alert(gs("You must enter a unique name."));
return}var j=uniqid(e+"_"+b),g=newelt("div");if("text"==k||"password"==k||"select-one"==k||"email"==k||"tel"==k||"url"==k){var n=newelt("label");set_innertext(n,b);var l=newelt("input","",ofja(j));l.type=ofja(h);n.appendChild(l);g.appendChild(n);"password"==k&&(g_eyeimgid=j+"toggleimg",l=newelt("a","eye",ofja(j)),l.id=ofja(j)+"toggle",l.href="#",l.className="eye",n=newelt("img","",ofja(g_eyeimgid)),n.id=ofja(g_eyeimgid),n.alt=gs("[Show]"),l.appendChild(n),g.appendChild(l))}else"textarea"==k?(l=newelt("textarea",
"",ofja(j)),g.appendChild(l)):"checkbox"==k&&(l=newelt("input","",ofja(j)),n=newelt("label"),n.for=ofja(j),set_innertext(n,b),g.appendChild(l),g.appendChild(n));l=newelt("a","",ofja(j)+"delete");n=newelt("div","","");set_innertext(l,"[ - ]");l.href="#";set_innertext(n,b);l.appendChild(n);l=d.createElement("div");l.id=j+"_div";l.appendChild(g);d.body.appendChild(l);event_handlers={};"password"==k&&(event_handlers[j+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,
this.id.length-6)),this);return!1});event_handlers[j+"delete"]=function(){var a=this.id.substring(0,this.id.length-6)+"_div";parent.delete_field(a,this.children[0].value,"");return!1};lpdbg("site","1 added event handler for "+j+"delete");fix_event_handlers();l={};l.otherfield=!data.editfields;l.name=b;l.type=k;"select-one"==k&&(l.faketype=h);l.value="";l.formname=e;l.checked=!1;l.urid="0";l.otherlogin="0";l.url="";l.htmlid=j;h=0;for(f in data.fields)data.fields.hasOwnProperty(f)&&f>h&&(h=f);data.fields[h+
1]=l;(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&a.update_fields(get_record_id(data),data.fields);a.increment_local_accts_version();a.rewritelocalfile();b="add=1&aid="+a.en(data.aid)+"&urid=0&name="+a.en(b)+"&type="+k;data.editfields||(b+="&formname="+a.en(e));b+="&auto=1";c=!1==c?"":"sharedfolderid="+a.en(c.id);a.saveFields(b,c,{url:base_url+"fields.php?"+b,aid:data.aid,postdata:c,param:null,newvalues:[]});d.getElementById("newname").value="";d.getElementById("newtype").selectedIndex=0;
d.getElementById("newformname")&&(d.getElementById("newformname").value="");d.getElementById("addfield").style.display="none"}}}function newelt(a,c,d){a=document.createElement(a);c&&(a.className=c);d&&(a.id=d);return a}
function getFieldsHTMLNodes(a){var c=getBG(),d=document.createElement("div"),b=newelt("link","","");b.rel="stylesheet";b.src="general.css";b.type="text/css";d.appendChild(b);if(!is_application(data)){event_handlers.addfieldlink=function(){parent.showaddfield();return!1};event_handlers.doaddfield=function(){parent.doaddfield()};var k=newelt("a","");k.href="#";k.id="addfieldlink";set_innertext(k,gs("Add Field"));d.appendChild(k);d.appendChild(document.createElement("br"));k=newelt("div","","addfield");
k.style.display="none";var b=newelt("label"),h=newelt("input","","newname");h.type="text";set_innertext(b,gs("Name:"));b.appendChild(h);k.appendChild(b);k.appendChild(newelt("br"));b=newelt("label");set_innertext(b,gs("Type:"));var h=newelt("select","","newtype"),e=newelt("option","","");e.value="text";set_innertext(e,gs("Text"));var f=newelt("option","","");f.value="password";set_innertext(f,gs("Password"));var j=newelt("option","","");j.value="select-one";set_innertext(j,gs("Select"));var g=newelt("option",
"","");g.value="checkbox";set_innertext(g,gs("Checkbox"));h.appendChild(e);h.appendChild(f);h.appendChild(j);h.appendChild(g);b.appendChild(h);k.appendChild(b);k.appendChild(newelt("br"));data.editfields||(e=newelt("label"),set_innertext(e,gs("Form Name:")),e.appendChild(newelt("input","","newformname")),k.appendChild(e));e=newelt("input","","doaddfield");e.type="button";e.value=gs("Add");k.appendChild(e);k.appendChild(newelt("br"));k.appendChild(newelt("br"))}d.appendChild(k);var k=[],n;for(n in data.fields){var l=
data.fields[n],e=l.formname,b=is_application(data)?n:l.name,h=j=l.value?l.value:"",g=l.type,f=b+"_"+g+"_"+j;if("undefined"==typeof k[f]){k[f]=!0;f=uniqid(e+"_"+b);l.htmlid=f;e=newelt("div");if(is_application(data)&&""==g||"text"==g||"password"==g||"email"==g||"tel"==g||"url"==g)h=crypto_btoa(j),j=c.lpmdec(j,!0,a),l=newelt("input","",ofja(f)),l.value=j,j=newelt("label"),set_innertext(j,b),j.appendChild(l),e.appendChild(j),"password"==g&&(event_handlers[f+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,
this.id.length-6)),this);return!1},j=newelt("a","",ofja(f)+"toggle"),j.href="#",g=newelt("span","",""),set_innertext(g,gs("[Show]")),j.appendChild(g),e.appendChild(j),l.type="password",g_pw_field_ids.push(f));else if("textarea"==g)h=crypto_btoa(j),j=c.lpmdec(j,!0,a),g=newelt("label"),set_innertext(g,b),l=document.createElement("textarea","",ofja(f)),set_innertext(l,j),g.appendChild(l),e.appendChild(g);else if("select-one"==g){g=newelt("label");set_innertext(g,b);var l=newelt("select","",ofja(f)),
r=newelt("option");r.value=j;set_innertext(r,j);l.appendChild(r);g.appendChild(l);e.appendChild(g)}else if("checkbox"==g||"radio"==g){j=l.checked?" checked":"";if("radio"==g&&""==j)continue;j=newelt("input","",ofja(f));j.type=ofja(g);j.checked=!0;e.appendChild(j);j=newelt("label");j.for=ofja(f);set_innertext(j,b);e.appendChild(j)}else continue;is_application(data)||(event_handlers[f+"delete"]=function(){var a=this.children,b=encodeURIComponent(get_innertext(a[0])),a=AES.hex2bin(get_innertext(a[1])),
c=this.id.substring(0,this.id.length-6)+"_div";parent.delete_field(c,b,a);return!1},lpdbg("site","2 added event handler for "+f+"delete"),j=newelt("a","",ofja(f)+"delete"),set_innertext(j,"[ - ]"),j.href="#",g=newelt("div","",ofja(f)+"value"),l=newelt("div","",ofja(f)+"origval"),g.style.display="none",set_innertext(g,b),l.style.display="none",set_innertext(l,AES.bin2hex(h)),e.appendChild(j),j.appendChild(g),j.appendChild(l));b=newelt("div","",ofja(f)+"_div");b.appendChild(e);d.appendChild(b)}}return d}
function delete_field(a,c,d){try{if(confirm(gs("Are you sure you would like to delete this field?"))){var b=getBG(),k=issharedfolder(b.g_shares,data.group);if(checkreadonly(k)){var h=document.getElementById("fields").contentWindow.document;if(h.getElementById(a)){h.getElementById(a).style.display="none";for(var e in data.fields)if(data.fields.hasOwnProperty(e)&&data.fields[e].name==c){var f=data.fields[e].value;is_encrypted_field(data.fields[e].type)&&(f=crypto_btoa(f));f==d&&("undefined"!=typeof data.fields.splice?
data.fields.splice(e,1):delete data.fields[e])}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_fields(get_record_id(data),data.fields);b.increment_local_accts_version();b.rewritelocalfile();var j="delete=1&aid="+b.en(get_record_id(data))+"&urid=0&name="+b.en(c)+"&value="+b.en(d),j=j+"&auto=1",g=!1==k?"":"sharedfolderid="+b.en(k.id);b.saveFields(j,g,{url:base_url+"fields.php?"+j,aid:data.aid,postdata:g,param:null,newfields:[]})}else alert("Sorry, deletion of the field failed. Please re-save the site.")}}}catch(n){console_log("caught exception in delete_field: "+
n.message)}}function dodel(){getBG().deleteAid(get_record_id(data),window,!1,!1,function(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)})}function doshare(){if(!check_for_changes()||confirm(gs("Are you sure you want to share this item?  Doing so will cause you to lose any changes you have made to this item!"))){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&share="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}
function docancel(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)}function show_history(a){if(!check_for_changes()||confirm(gs("Are you sure you want to view history?  Doing so will cause you to lose any changes you have made to this item!"))){var c=getBG();c.unlock_plug2web();c.openbaseurl("?ac=1&"+(a?"username":"password")+"history="+c.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}var logged=!1;
function toggle_password(a,c){if("password"==a.type){if(existing){var d=getBG();if(null!=data.sharedfromaid&&""!=data.sharedfromaid&&"0"!=data.sharedfromaid&&"null"!=data.sharedfromaid){alert(gs("This is a shared site. You are not permitted to view the password."));return}if(d.g_prompts.view_pw_prompt){g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?d.security_prompt(function(){a.type="text";c.children[0].children[0].src=get_eye_src(a.type,"glow");
c.children[0].children[0].setAttribute("alt",gs("[Hide]"));set_innertext(c.children[0].children[1],gs("Hide Password"))}):d.security_prompt(function(){a.type="text";c.innerHTML=gs("[Hide]")});return}}existing&&!logged&&(d.loglogin(get_record_id(data)),logged=!0);a.type="text";g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type,"glow"),c.children[0].children[0].setAttribute("alt",gs("[Hide]")),set_innertext(c.children[0].children[1],
gs("Hide Password"))):c.innerHTML=gs("[Hide]")}else a.type="password",g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type),c.children[0].children[0].setAttribute("alt",gs("[Show]")),set_innertext(c.children[0].children[1],gs("Show Password"))):c.innerHTML=gs("[Show]")}function gsproper(a){return gs(a+"proper")!=a+"proper"?gs(a+"proper"):gs(a)}
function check_for_changes(){var a=getBG(),c=document.getElementById("url").value,d=document.getElementById("name").value,b=document.getElementById("group").value,k=document.getElementById("username").value,h=document.getElementById("password").value,e=getSecureNoteFromFields(),f=document.getElementById("fav").checked,j=document.getElementById("never_autofill").checked,g=document.getElementById("pwprotect").checked,n=document.getElementById("autologin").checked,l=issharedfolder(a.g_shares,b),l=!1==
l?a.g_local_key:l.sharekey;return is_application(data)?c!=data.appname||d!=data.name||b!=data.group||k!=getusernamefromacct(data)||h!=getpasswordfromacct(data)||e!=a.lpmdec(data.extra,!0,l)||f!=("1"==data.fav)||g!=data.pwprotect||n!=("1"==data.autologin):c!=data.url||d!=data.name||b!=data.group||k!=data.unencryptedUsername||h!=a.lpmdec(data.password,!0,l)||e!=a.lpmdec(data.extra,!0,l)||f!=("1"==data.fav)||j!=data.never_autofill||g!=data.pwprotect||n!=data.autologin}
function doeditfields(){var a=getBG();if(!check_for_changes()||confirm(is_application(data)?gs("LoseChangesApp"):gs("LoseChanges"))){a.g_site_data=[];for(var c in data)a.g_site_data[c]=data[c];a.g_site_data.editfields=1;a.set_editfieldsopener(window);a.openURL(getchromeurl("site.html"),null,a.g_site_data)}}function showattach(a){a.getAttribute("src_hidden")&&a.getAttribute("src_hidden").length?getBG().showImageAttach(a.getAttribute("src_hidden")):openattach(a)}
function openattach(a){var c=a.getAttribute("filename")?a.getAttribute("filename"):"";getBG().openAttach(get_record_id(data),a.getAttribute("attachid"),c)}function addattach(){getBG().have_binary()?getBG().addAttach(function(){getBG().g_ischrome&&addattachcb()}):confirm(gs("This feature requires the binary version of this browser extension.  Would you like to install it now?"))&&getBG().install_binary()}
function addThumbnail(a,c,d,b,k,h){var e=get_extension_from_mimetype(c),f=check_filename_badchars(e),j=null,j=f==FILENAME_FRAGMENT_VALID?"."+e:0==f.length||f==FILENAME_FRAGMENT_EMPTY?"":"."+gs(e);if(k&&h)try{var g=AES.hex2bin(lpdec(k,h));b=lpdec(b,g)}catch(n){b=""}if(null===b||""==b)b="attachment"+num_attachments+j;e=document.getElementById("attachtable");f=document.createElement("tr");j=document.createElement("td");j.id=a;j.style.height="28px";j.style.width="80%";j.style.background="url('images/paperclip.png') no-repeat 2px 2px #e6e6e6";
var l=document.createElement("span");l.style.fontWeight="bold";l.style.position="relative";l.style.left="32px";l.style.top="6px";l.style.cursor="pointer";l.appendChild(document.createTextNode(b));d&&""!=d&&0==c.indexOf("data:image")?(l.setAttribute("attachid",a),k?(getBG().fastDecryptAttachment(a,c,d,k,h,function(a){getBG().g_ischrome&&(a&&a.length?l.setAttribute("src_hidden",c+";base64,"+a):l.setAttribute("src_hidden",""))}),l.addEventListener("click",function(){attachment_action_menu(this,showattach)})):
(d&&d.length?l.setAttribute("src_hidden",c+";base64,"+d):l.setAttribute("src_hidden",""),getBG().have_binary()?l.addEventListener("click",function(){attachment_action_menu(this,showattach)}):l.addEventListener("click",function(){showattach(this)}))):(l.setAttribute("attachid",a),getBG().have_binary()?l.addEventListener("click",function(){attachment_action_menu(this,openattach)}):l.addEventListener("click",function(){openattach(this)}));d=document.createElement("span");d.className="attachx";d.setAttribute("attachid",
a);d.addEventListener("click",function(){rmattach(this)});d.innerHTML="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";j.appendChild(l);j.appendChild(d);f.appendChild(j);e.insertBefore(f,e.firstChild);attachnum++}function createAttachId(){for(;;){var a=Math.floor(99999*Math.random()),c;for(c in data.attaches)if(data.attaches.hasOwnProperty(c)&&data.attaches[c].id==get_record_id(data)+"-"+a)break;for(c=0;c<attaches.length&&!("undefined"!=typeof attaches[c]&&attaches[c].id==a);c++);return a}}
function rmattach(a){a=a.getAttribute("attachid");if(confirm(gs("Are you sure you would like to remove this attachment?"))){if("undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&a==data.attaches[c].id&&(removedattach[removedattach.length]=a);delete attaches[a];delThumbnail(a)}}
function delThumbnail(a){for(var c=document.getElementById("attachtable"),d=0;d<c.children.length;d++){var b=c.children[d];if(b.children&&b.children.length&&b.children[0].id==a){c.removeChild(b);break}}}
function attachment_action_doSave(){if(null!=open_attach_target){var a=open_attach_target.getAttribute("filename")?open_attach_target.getAttribute("filename"):"";getBG().exportAttachment(get_record_id(data),open_attach_target.getAttribute("attachid"),a)}else alarm("error, trying to save an attachment that does not exist");close_attach_list()}
function clearData(){for(var a=document.getElementsByTagName("input"),c=0;c<a.length;c++)"button"!=a[c].type&&(a[c].value="");a=document.getElementsByTagName("textarea");for(c=0;c<a.length;c++)a[c].value=""}function uniqid(a){a||(a="");return"a"+SHA256(a+"_"+(new Date).getTime()+"_"+Math.floor(100*Math.random()))}function setup_eye_events(a){g_eye_show&&(a.getElementById("passwordtoggle"),a.getElementById("passwordtoggleimg").style.verticalAlign="bottom")}
function eye_over(a){if(!(null==a||null==a.target)){var c=document.getElementById("passwordtoggleimg"),d=document.getElementById("password");a.target==c&&(c.src=get_eye_src(d.type,"glow"))}}function eye_out(a){if(!(null==a||null==a.target)){var c=document.getElementById("passwordtoggleimg"),d=document.getElementById("password");a.target==c&&(c.src=get_eye_src(d.type))}}function get_eye_src(a){return"password"==a?"images/eye-shown.png":"images/eye-hidden.png"}var CPW_WAKETIME=97,my_aid=null;
function docpwbtn(){var a=getBG(),c=document;if(!c||!a||!data)return!1;var d=data.aid,b=data.url;g_cpwbot&&b?"undefined"!=typeof a.dopwchange?(g_start_time=(new Date).getTime(),a.cpwbot_preinit(),g_cpw_progress_ctr=20,show_cpw_dialog("progress"),setTimeout(function(){insert_cpw_placeholder_msg(c,gs("LastPass is loading..."))},5003),setTimeout(function(){cpw_status_check()},CPW_WAKETIME),g_ischrome?chrome.tabs.getSelected(function(b){a.dopwchange(d,!1,b)}):a.dopwchange(d,!1)):pass:pass;return!1}
function docpwdebug(){var a=getBG(),c=document;if(!c||!a||!data)return!1;if(g_cpwbot){if(document.getElementById("cpwmsgdiv"))return!1;a=c.createElement("div");a.style.height="200px";a.style.width="100%";a.style.overflow="auto";a.style.backgroundColor="blue";a.style.color="yellow";a.style.padding="3px";a.id="cpwmsgdiv";var d=c.getElementById("sitebody");d?d.appendChild(a):c.body.appendChild(a)}return!1}var g_cpw_progress_ctr=0,g_lastmsg="";
function cpw_status_check(){var a=getBG(),c=document;if(!c||!a||!data)return!1;var d=!1,b=!1,k=!1,h=!1,e=!1,f=!1;(c=c.getElementById("cpwmsgdiv"))&&(g_ischrome?set_innertext(c,a.cpwbot_get_user_debug_messages()):a.cpwbot_get_user_debug_messages());g_ischrome?(a=a.cpwbot_get_dialog_msg(),cpw_progress_update(a)):a.cpwbot_get_dialog_msg();a=get_current_state(!0);lpdbg("site","BG.current_state is "+a);switch(a){case "FAIL":b=d=!0;break;case "CAPTCHA":k=b=d=!0;break;case "DOCAPTCHA":h=!0;break;case "TIMEOUT":f=
b=d=!0;break;case "FAIL_PW_SAVED":e=b=d=!0;break;case "DONE":case "OK":d=!0;break;case 0:case null:d=!1}form_refresh();h?g_start_time=(new Date).getTime():(new Date).getTime()>g_start_time+POLL_MAXTIME&&(b=d=!0,lpdbg("site","max timeout"));d?(b?k?show_cpw_dialog("captcha"):f?show_cpw_dialog("timeout"):e?show_cpw_dialog("fail_pw_saved"):show_cpw_dialog("fail"):show_cpw_dialog("dismiss"),g_ischrome?setTimeout(function(){form_refresh()},3001):setTimeout(function(){get_data("siterefresh",function(){form_refresh()})},
3001)):setTimeout(function(){cpw_status_check()},CPW_WAKETIME)}
function form_refresh(){var a=getBG(),c=document;if(!c||(!a||!data)||!a.lploggedin)return!1;var d=(new Date).getTime(),b=0;if(my_aid){var k=get_record(my_aid,!0);if(k){var h="";"undefined"!=typeof a.g_pending_pw_change&&(h=a.lpdec_acct(a.g_pending_pw_change[my_aid],k,a.g_shares));var e=getpasswordfromacct(k);if(k.save_all){c=document.getElementById("fields").contentWindow.document;for(b=0;b<g_pw_field_ids.length;b++){var f=c.getElementById(g_pw_field_ids[b]);if(f){var j=f.value;if(e&&f&&h&&h!=e&&
(e==j||h==j))lpdbg("site","using pending pw instead of g_sites"),e=h;e&&f&&(j===e?console.warn("REFRESH: no change"):j&&e&&(f.value=e,lpdbg("site","REFRESH: reset password iframe field from "+(a.g_show_pw_in_logs?j:"REDACTED")+" to "+(a.g_show_pw_in_logs?e:"REDACTED"))));update_SaveButton()}}}else{f=c.getElementById("password");j=f.value;if(e&&f&&h&&h!=e&&(e==j||h==j))lpdbg("site","using pending pw instead of g_sites"),e=h,b=d/1E3;e&&f&&(j!==e&&j&&e)&&(f.value=e,lpdbg("site","REFRESH: reset password from "+
(a.g_show_pw_in_logs?j:"REDACTED")+" to "+(a.g_show_pw_in_logs?e:"REDACTED")),h=issharedfolder(a.g_shares,data.group),data.password=a.lpmenc(e,!0,!1==h?a.g_local_key:h.sharekey),0<b?pw_age_update(b):pw_age_update(k.last_pwchange_gmt),update_password_meter("",c.getElementById("password").value),update_SaveButton())}}}return!1}
function show_cpw_button(a){var c=getBG(),d=document;if(!d||!c||!a)return!1;var b=!1;!g_cpwbot&&("undefined"!=typeof c.g_cpwbot&&c.g_cpwbot)&&(g_cpwbot=c.g_cpwbot);c=issharedfolder(c.g_shares,a.group);a&&(c?(checkreadonly(c,!0)?(b=!1,lpdbg("site","in shared folder, writable")):(b=!0,lpdbg("site","in shared folder, readonly")),"1"===c.associative&&lpdbg("site","entry is in linked account")):a.individualshare?null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?
(lpdbg("site","individual share, readonly"),b=!0):(lpdbg("site","individual share, writable"),b=!1):b=!1);if(g_cpwbot&&a&&"1"==a.pwch&&!b)if(a.save_all)enable_cpw_field_btn(document);else{if(a=d.getElementById("cpwbtnmini"))a.addEventListener("click",function(){document.getElementById("cpwbtnmini").classList.contains("btn_disabled")||show_cpw_dialog("new")}),a.style.fontSize="12px",a.style.display="inline-block";if(a=d.getElementById("pwspacer"))a.style.display="inline-block",a.style.width="50px"}else{if(a=
d.getElementById("cpwbtnmini"))a.style.display="none";if(a=d.getElementById("pwspacer"))a.style.display="none";if(d=d.getElementById("cpwfieldbtn"))d.style.display="none"}}
function pw_age_update(a){var c=getBG(),d=document;if(!d||!c||!data)return!1;a=parseInt(a);var b=(new Date).getTime(),c=180,c=0,b=null===b?0:parseInt(b/1E3)-60*c,c="Never";if(!a||"number"!=typeof a||!b||isNaN(a)||isNaN(b)||b<a){c="";if(a=d.getElementById("pwagelabel"))a.style.display="none";pass}else d.getElementById("pwagelabel"),a=b-a,60>a?c=a.toString()+" "+(1==a?gs("second"):gs("seconds")):3600>a?(a=parseInt(a/60),c=a.toString()+" "+(1==a?gs("minute"):gs("minutes"))):86400>a?(a=parseInt(a/3600),
c=a.toString()+" "+(1==a?gs("hour"):gs("hours"))):604800>a?(a=parseInt(a/86400),c=a.toString()+" "+(1==a?gs("day"):gs("days"))):2592E3>a?(a=parseInt(a/604800),c=a.toString()+" "+(1==a?gs("week"):gs("weeks"))):31536E3>a?(a=parseInt(a/2592E3),c=a.toString()+" "+(1==a?gs("month"):gs("months"))):(a=parseInt(a/31536E3),c=a.toString()+" "+(1==a?gs("year"):gs("years")));a=d.getElementById("pwagediv");a.style.fontStyle="italic";a&&(set_innertext(a,c),d.getElementById("pwagelabel").style.display="inline")}
function hide_cpw_dialog(){var a=getBG(),c=document;if(!c||!a||!data)return!1;c.getElementById("pwcontainer");var d=c.getElementById("cpwdialog");d&&(d.style.display="none");if(c=c.getElementById("modalbg"))c.style.display="none";"undefined"!=typeof a.cpwbot_halt&&(c=get_current_state(),"FAIL"!=c&&("CAPTCHA"!=c&&"DONE"!=c&&"OK"!=c&&"TIMEOUT"!=c&&0!=c&&null!==c)&&a.cpwbot_halt());data&&data.openchpw&&a.close_cpw_tabs()}var event_flags=0,EV_CX=1,EV_OK=2,g_cpw_heard_from_bg=!1;
function show_cpw_dialog(a,c,d,b,k){var h=getBG(),e=document;if(!e||!h||!data)return!1;e.getElementById("notesrow1");e.getElementById("pwcontainer");h=e.getElementById("modalbg");h.style.width=e.body.clientWidth;h.style.height=e.body.clientHeight;h.style.display="block";var h=e.getElementById("dlghdg"),f=e.getElementById("dlghtml");f.style.fontSize="12px";var j=e.getElementById("bcnd"),g=e.getElementById("bokd"),n=e.getElementById("bdis"),l=null;j&&0==(event_flags&EV_CX)&&(j.addEventListener("click",
function(){hide_cpw_dialog()}),e.getElementById("dlgclose").addEventListener("click",function(){hide_cpw_dialog()}),n.addEventListener("click",function(){hide_cpw_dialog()}),event_flags|=EV_CX);g&&0==(event_flags&EV_OK)&&(g.addEventListener("click",function(a){docpwbtn(a);return!1}),event_flags|=EV_OK);set_innertext(j,gs("No, Thanks"));set_innertext(g,gs("Change Password Now"));set_innertext(n,gs("Dismiss"));set_innertext(h,sprintf(gs("%s Password One-Click Change"),"LastPass"));switch(a){case "new":g_cpw_heard_from_bg=
!1;f.innerHTML="<p>"+sprintf(gs("%s will now attempt to change your password to a strong, generated password that will be saved in your vault and known only to you."),"LastPass")+"</p><br/><p>"+sprintf(gs("In order to complete the process, %s will have to log in to %s and navigate through a number of windows quickly. It is normal to see windows flashing and changing quickly, and may take several moments. We'll let you know when you're all set!"),"LastPass","<b>"+of(data.name)+"</b>")+"</p>";j.style.display=
"block";g.style.display="block";n.style.display="none";break;case "progress":f.innerHTML="<b>"+gs("Overall Progress:")+"</b><br /><div class='progress_container'><div class='progress_bar' id='progress_bar'></div></div><div id='stepbystep'></div><div id='advanced'></div>";e.getElementById("progress_bar").style.width="10%";j.style.display="none";g.style.display="none";n.style.display="none";break;case "update":e.getElementById("progress_bar").style.width=c+"%";d&&(a=e.createElement("p"),"DOCAPTCHA"==
get_current_state()&&(a.className="boldred"),d=e.createTextNode(d),a.appendChild(d),e.getElementById("stepbystep").appendChild(a),g_cpw_heard_from_bg||(g_cpw_heard_from_bg=!0,(l=e.getElementById("cpw_placeholder_msg"))&&l.parentNode.removeChild(l)));b&&(a=e.createElement("i"),d=e.createTextNode(gs("Complete!")),a.appendChild(d),(b=e.getElementById("stepbystep").lastChild)&&b.appendChild(a));k&&(a=e.createElement("p"),d=e.createTextNode(k),a.appendChild(d),e.getElementById("advanced").appendChild(a));
break;case "dismiss":f.innerHTML="<br><br><p>"+sprintf(gs("Congratulations! Your password for %s was updated, and is now saved in your LastPass vault. Your change will sync on every device."),"<b>"+of(data.name)+"</b>")+"</p>";j.style.display="none";g.style.display="none";n.style.display="block";set_innertext(n,gs("OK"));break;case "fail":f.innerHTML="<br><br><p>"+sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),"<b>"+of(data.name)+
"</b>")+"</p>";j.style.display="none";g.style.display="none";n.style.display="block";break;case "captcha":f.innerHTML="<br><br><p>"+gs("Unable to proceed, the website does not allow automated password change.")+"</p>";j.style.display="none";g.style.display="none";n.style.display="block";break;case "timeout":f.innerHTML="<br><br><p>"+gs("Timed out waiting for the page to load.  Retry?");NaN;j.style.display="none";g.style.display="none";n.style.display="block";break;case "fail_pw_saved":f.innerHTML=
"<br><br><p>"+sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),"<b>"+of(data.name)+"</b>")+gs("The random password that was generated has been saved to your vault.")+"</p>",j.style.display="none",g.style.display="none",n.style.display="block"}k=e.getElementById("cpwdialog");k.style.display="block";k.style.height="250px";k.style.width="470px";k.style.left=(parseInt(e.body.clientWidth)-470)/2+"px";k.style.top=(parseInt(e.body.clientHeight)-
470)/2+"px";g_ischrome||(g_cpwbot_pwchangestate="init_state_dingbats")}function notehist(){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&notehistory="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}var g_cpwbot_pwchangestate=null;function cpw_progress_update(a){a&&a!=g_lastmsg&&(g_lastmsg=a,g_cpw_progress_ctr+=20,90<g_cpw_progress_ctr&&(g_cpw_progress_ctr=95),show_cpw_dialog("update",g_cpw_progress_ctr,a,!1,""))}
function get_current_state(a){if(g_ischrome)return getBG().cpwbot_getpwchangestate();var c=g_cpwbot_pwchangestate;a&&getBG().cpwbot_getpwchangestate();return c}
function enable_cpw_field_btn(a){var c=a.getElementById("cpwfieldbtn");c&&(c.addEventListener("click",function(){!a.getElementById("cpwfieldbtn").classList.contains("btn_disabled")&&!a.getElementById("cpwbtnmini").classList.contains("btn_disabled")&&show_cpw_dialog("new")}),c.style.fontSize="12px",c.style.display="inline-block",c.style.marginTop="5px",c.style.marginBottom="5px")}
function accelerator_key_handler(a){if(!g_do_keyaccel)return!0;if(!a||!a.keyCode)return!1;var c=!0,d=!1;try{"undefined"!=typeof navigator&&"undefined"!=typeof navigator.platform&&0==navigator.platform.toLowerCase().indexOf("mac")&&(c=!1,d=!0)}catch(b){}var k=document;if(!k)return!1;switch(a.keyCode){case KEY_S:if(a.ctrlKey&&d||a.altKey&&c)"function"!=typeof a.preventDefault&&a.preventDefault(),is_savebtn_disabled(k)||dosave(),LP_stopEventPropagation(a)}return!0}
function is_savebtn_disabled(a){a||(a=document);a=a.getElementById("save");return!a?!0:0<=a.className.indexOf("btn_disabled")}function insert_cpw_placeholder_msg(a,c){a||(a=document);var d=a.getElementById("cpw_placeholder_msg");if(c&&!g_cpw_heard_from_bg&&null===d){var d=a.createElement("p"),b=a.createTextNode(c);d.id="cpw_placeholder_msg";d.appendChild(b);a.getElementById("stepbystep").appendChild(d)}};
